/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TipsInterviewRouteImport } from './routes/tips-interview'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as TemplateRouteImport } from './routes/template'
import { Route as SyaratKetentuanRouteImport } from './routes/syarat-ketentuan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivateCoachingRouteImport } from './routes/private-coaching'
import { Route as PanduanCvAtsRouteImport } from './routes/panduan-cv-ats'
import { Route as LupaPasswordRouteImport } from './routes/lupa-password'
import { Route as LowonganRouteImport } from './routes/lowongan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as HargaRouteImport } from './routes/harga'
import { Route as FiturRouteImport } from './routes/fitur'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TipsInterviewSlugRouteImport } from './routes/tips-interview.$slug'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as SecurityTxtRouteImport } from './routes/security.txt'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as ManifestWebmanifestRouteImport } from './routes/manifest.webmanifest'
import { Route as LowonganSlugRouteImport } from './routes/lowongan.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiHeadersCheckRouteImport } from './routes/api.headers-check'
import { Route as ApiAiCvReviewRouteImport } from './routes/api/ai-cv-review'
import { Route as AuthenticatedSimulasiWawancaraRouteImport } from './routes/_authenticated/simulasi-wawancara'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedLamaranRouteImport } from './routes/_authenticated/lamaran'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedAnalitikRouteImport } from './routes/_authenticated/analitik'
import { Route as AuthenticatedAkunRouteImport } from './routes/_authenticated/akun'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedToolsIndexRouteImport } from './routes/_authenticated/tools.index'
import { Route as AuthenticatedCvIndexRouteImport } from './routes/_authenticated/cv.index'
import { Route as AuthenticatedCvReviewIndexRouteImport } from './routes/_authenticated/cv-review.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSimulasiWawancaraIdRouteImport } from './routes/_authenticated/simulasi-wawancara.$id'
import { Route as AuthenticatedScoreCvIdRouteImport } from './routes/_authenticated/score.$cvId'
import { Route as AuthenticatedCvIdRouteImport } from './routes/_authenticated/cv.$id'
import { Route as AuthenticatedCvReviewCvIdRouteImport } from './routes/_authenticated/cv-review.$cvId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin/templates'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin/jobs'
import { Route as AuthenticatedToolsKeywordCvIdRouteImport } from './routes/_authenticated/tools.keyword.$cvId'
import { Route as AuthenticatedToolsCoverLetterCvIdRouteImport } from './routes/_authenticated/tools.cover-letter.$cvId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsInterviewRoute = TipsInterviewRouteImport.update({
  id: '/tips-interview',
  path: '/tips-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateRoute = TemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratKetentuanRoute = SyaratKetentuanRouteImport.update({
  id: '/syarat-ketentuan',
  path: '/syarat-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateCoachingRoute = PrivateCoachingRouteImport.update({
  id: '/private-coaching',
  path: '/private-coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanCvAtsRoute = PanduanCvAtsRouteImport.update({
  id: '/panduan-cv-ats',
  path: '/panduan-cv-ats',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaPasswordRoute = LupaPasswordRouteImport.update({
  id: '/lupa-password',
  path: '/lupa-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LowonganRoute = LowonganRouteImport.update({
  id: '/lowongan',
  path: '/lowongan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const HargaRoute = HargaRouteImport.update({
  id: '/harga',
  path: '/harga',
  getParentRoute: () => rootRouteImport,
} as any)
const FiturRoute = FiturRouteImport.update({
  id: '/fitur',
  path: '/fitur',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsInterviewSlugRoute = TipsInterviewSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TipsInterviewRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityTxtRoute = SecurityTxtRouteImport.update({
  id: '/security/txt',
  path: '/security/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestWebmanifestRoute = ManifestWebmanifestRouteImport.update({
  id: '/manifest/webmanifest',
  path: '/manifest/webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const LowonganSlugRoute = LowonganSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LowonganRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiHeadersCheckRoute = ApiHeadersCheckRouteImport.update({
  id: '/api/headers-check',
  path: '/api/headers-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCvReviewRoute = ApiAiCvReviewRouteImport.update({
  id: '/api/ai-cv-review',
  path: '/api/ai-cv-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimulasiWawancaraRoute =
  AuthenticatedSimulasiWawancaraRouteImport.update({
    id: '/simulasi-wawancara',
    path: '/simulasi-wawancara',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLamaranRoute = AuthenticatedLamaranRouteImport.update({
  id: '/lamaran',
  path: '/lamaran',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalitikRoute = AuthenticatedAnalitikRouteImport.update({
  id: '/analitik',
  path: '/analitik',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAkunRoute = AuthenticatedAkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCvIndexRoute = AuthenticatedCvIndexRouteImport.update({
  id: '/cv/',
  path: '/cv/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCvReviewIndexRoute =
  AuthenticatedCvReviewIndexRouteImport.update({
    id: '/cv-review/',
    path: '/cv-review/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSimulasiWawancaraIdRoute =
  AuthenticatedSimulasiWawancaraIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSimulasiWawancaraRoute,
  } as any)
const AuthenticatedScoreCvIdRoute = AuthenticatedScoreCvIdRouteImport.update({
  id: '/score/$cvId',
  path: '/score/$cvId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCvIdRoute = AuthenticatedCvIdRouteImport.update({
  id: '/cv/$id',
  path: '/cv/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCvReviewCvIdRoute =
  AuthenticatedCvReviewCvIdRouteImport.update({
    id: '/cv-review/$cvId',
    path: '/cv-review/$cvId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedToolsKeywordCvIdRoute =
  AuthenticatedToolsKeywordCvIdRouteImport.update({
    id: '/tools/keyword/$cvId',
    path: '/tools/keyword/$cvId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedToolsCoverLetterCvIdRoute =
  AuthenticatedToolsCoverLetterCvIdRouteImport.update({
    id: '/tools/cover-letter/$cvId',
    path: '/tools/cover-letter/$cvId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/fitur': typeof FiturRoute
  '/harga': typeof HargaRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/lowongan': typeof LowonganRouteWithChildren
  '/lupa-password': typeof LupaPasswordRoute
  '/panduan-cv-ats': typeof PanduanCvAtsRoute
  '/private-coaching': typeof PrivateCoachingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/template': typeof TemplateRoute
  '/tentang': typeof TentangRoute
  '/tips-interview': typeof TipsInterviewRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/akun': typeof AuthenticatedAkunRoute
  '/analitik': typeof AuthenticatedAnalitikRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lamaran': typeof AuthenticatedLamaranRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/simulasi-wawancara': typeof AuthenticatedSimulasiWawancaraRouteWithChildren
  '/api/ai-cv-review': typeof ApiAiCvReviewRoute
  '/api/headers-check': typeof ApiHeadersCheckRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lowongan/$slug': typeof LowonganSlugRoute
  '/manifest/webmanifest': typeof ManifestWebmanifestRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/security/txt': typeof SecurityTxtRoute
  '/share/$token': typeof ShareTokenRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/tips-interview/$slug': typeof TipsInterviewSlugRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/cv-review/$cvId': typeof AuthenticatedCvReviewCvIdRoute
  '/cv/$id': typeof AuthenticatedCvIdRoute
  '/score/$cvId': typeof AuthenticatedScoreCvIdRoute
  '/simulasi-wawancara/$id': typeof AuthenticatedSimulasiWawancaraIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/cv-review/': typeof AuthenticatedCvReviewIndexRoute
  '/cv/': typeof AuthenticatedCvIndexRoute
  '/tools/': typeof AuthenticatedToolsIndexRoute
  '/tools/cover-letter/$cvId': typeof AuthenticatedToolsCoverLetterCvIdRoute
  '/tools/keyword/$cvId': typeof AuthenticatedToolsKeywordCvIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/fitur': typeof FiturRoute
  '/harga': typeof HargaRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/lowongan': typeof LowonganRouteWithChildren
  '/lupa-password': typeof LupaPasswordRoute
  '/panduan-cv-ats': typeof PanduanCvAtsRoute
  '/private-coaching': typeof PrivateCoachingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/template': typeof TemplateRoute
  '/tentang': typeof TentangRoute
  '/tips-interview': typeof TipsInterviewRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/akun': typeof AuthenticatedAkunRoute
  '/analitik': typeof AuthenticatedAnalitikRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lamaran': typeof AuthenticatedLamaranRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/simulasi-wawancara': typeof AuthenticatedSimulasiWawancaraRouteWithChildren
  '/api/ai-cv-review': typeof ApiAiCvReviewRoute
  '/api/headers-check': typeof ApiHeadersCheckRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lowongan/$slug': typeof LowonganSlugRoute
  '/manifest/webmanifest': typeof ManifestWebmanifestRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/security/txt': typeof SecurityTxtRoute
  '/share/$token': typeof ShareTokenRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/tips-interview/$slug': typeof TipsInterviewSlugRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/cv-review/$cvId': typeof AuthenticatedCvReviewCvIdRoute
  '/cv/$id': typeof AuthenticatedCvIdRoute
  '/score/$cvId': typeof AuthenticatedScoreCvIdRoute
  '/simulasi-wawancara/$id': typeof AuthenticatedSimulasiWawancaraIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/cv-review': typeof AuthenticatedCvReviewIndexRoute
  '/cv': typeof AuthenticatedCvIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/tools/cover-letter/$cvId': typeof AuthenticatedToolsCoverLetterCvIdRoute
  '/tools/keyword/$cvId': typeof AuthenticatedToolsKeywordCvIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/fitur': typeof FiturRoute
  '/harga': typeof HargaRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/lowongan': typeof LowonganRouteWithChildren
  '/lupa-password': typeof LupaPasswordRoute
  '/panduan-cv-ats': typeof PanduanCvAtsRoute
  '/private-coaching': typeof PrivateCoachingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/template': typeof TemplateRoute
  '/tentang': typeof TentangRoute
  '/tips-interview': typeof TipsInterviewRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/akun': typeof AuthenticatedAkunRoute
  '/_authenticated/analitik': typeof AuthenticatedAnalitikRoute
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lamaran': typeof AuthenticatedLamaranRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/simulasi-wawancara': typeof AuthenticatedSimulasiWawancaraRouteWithChildren
  '/api/ai-cv-review': typeof ApiAiCvReviewRoute
  '/api/headers-check': typeof ApiHeadersCheckRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lowongan/$slug': typeof LowonganSlugRoute
  '/manifest/webmanifest': typeof ManifestWebmanifestRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/security/txt': typeof SecurityTxtRoute
  '/share/$token': typeof ShareTokenRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/tips-interview/$slug': typeof TipsInterviewSlugRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/cv-review/$cvId': typeof AuthenticatedCvReviewCvIdRoute
  '/_authenticated/cv/$id': typeof AuthenticatedCvIdRoute
  '/_authenticated/score/$cvId': typeof AuthenticatedScoreCvIdRoute
  '/_authenticated/simulasi-wawancara/$id': typeof AuthenticatedSimulasiWawancaraIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/cv-review/': typeof AuthenticatedCvReviewIndexRoute
  '/_authenticated/cv/': typeof AuthenticatedCvIndexRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/_authenticated/tools/cover-letter/$cvId': typeof AuthenticatedToolsCoverLetterCvIdRoute
  '/_authenticated/tools/keyword/$cvId': typeof AuthenticatedToolsKeywordCvIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/fitur'
    | '/harga'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/login'
    | '/lowongan'
    | '/lupa-password'
    | '/panduan-cv-ats'
    | '/private-coaching'
    | '/register'
    | '/reset-password'
    | '/syarat-ketentuan'
    | '/template'
    | '/tentang'
    | '/tips-interview'
    | '/verify-email'
    | '/admin'
    | '/akun'
    | '/analitik'
    | '/compare'
    | '/dashboard'
    | '/lamaran'
    | '/referral'
    | '/simulasi-wawancara'
    | '/api/ai-cv-review'
    | '/api/headers-check'
    | '/blog/$slug'
    | '/lowongan/$slug'
    | '/manifest/webmanifest'
    | '/robots/txt'
    | '/security/txt'
    | '/share/$token'
    | '/sitemap/xml'
    | '/tips-interview/$slug'
    | '/admin/jobs'
    | '/admin/templates'
    | '/admin/users'
    | '/cv-review/$cvId'
    | '/cv/$id'
    | '/score/$cvId'
    | '/simulasi-wawancara/$id'
    | '/admin/'
    | '/cv-review/'
    | '/cv/'
    | '/tools/'
    | '/tools/cover-letter/$cvId'
    | '/tools/keyword/$cvId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/fitur'
    | '/harga'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/login'
    | '/lowongan'
    | '/lupa-password'
    | '/panduan-cv-ats'
    | '/private-coaching'
    | '/register'
    | '/reset-password'
    | '/syarat-ketentuan'
    | '/template'
    | '/tentang'
    | '/tips-interview'
    | '/verify-email'
    | '/akun'
    | '/analitik'
    | '/compare'
    | '/dashboard'
    | '/lamaran'
    | '/referral'
    | '/simulasi-wawancara'
    | '/api/ai-cv-review'
    | '/api/headers-check'
    | '/blog/$slug'
    | '/lowongan/$slug'
    | '/manifest/webmanifest'
    | '/robots/txt'
    | '/security/txt'
    | '/share/$token'
    | '/sitemap/xml'
    | '/tips-interview/$slug'
    | '/admin/jobs'
    | '/admin/templates'
    | '/admin/users'
    | '/cv-review/$cvId'
    | '/cv/$id'
    | '/score/$cvId'
    | '/simulasi-wawancara/$id'
    | '/admin'
    | '/cv-review'
    | '/cv'
    | '/tools'
    | '/tools/cover-letter/$cvId'
    | '/tools/keyword/$cvId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/fitur'
    | '/harga'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/login'
    | '/lowongan'
    | '/lupa-password'
    | '/panduan-cv-ats'
    | '/private-coaching'
    | '/register'
    | '/reset-password'
    | '/syarat-ketentuan'
    | '/template'
    | '/tentang'
    | '/tips-interview'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/akun'
    | '/_authenticated/analitik'
    | '/_authenticated/compare'
    | '/_authenticated/dashboard'
    | '/_authenticated/lamaran'
    | '/_authenticated/referral'
    | '/_authenticated/simulasi-wawancara'
    | '/api/ai-cv-review'
    | '/api/headers-check'
    | '/blog/$slug'
    | '/lowongan/$slug'
    | '/manifest/webmanifest'
    | '/robots/txt'
    | '/security/txt'
    | '/share/$token'
    | '/sitemap/xml'
    | '/tips-interview/$slug'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/users'
    | '/_authenticated/cv-review/$cvId'
    | '/_authenticated/cv/$id'
    | '/_authenticated/score/$cvId'
    | '/_authenticated/simulasi-wawancara/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/cv-review/'
    | '/_authenticated/cv/'
    | '/_authenticated/tools/'
    | '/_authenticated/tools/cover-letter/$cvId'
    | '/_authenticated/tools/keyword/$cvId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  FiturRoute: typeof FiturRoute
  HargaRoute: typeof HargaRoute
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  KontakRoute: typeof KontakRoute
  LoginRoute: typeof LoginRoute
  LowonganRoute: typeof LowonganRouteWithChildren
  LupaPasswordRoute: typeof LupaPasswordRoute
  PanduanCvAtsRoute: typeof PanduanCvAtsRoute
  PrivateCoachingRoute: typeof PrivateCoachingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SyaratKetentuanRoute: typeof SyaratKetentuanRoute
  TemplateRoute: typeof TemplateRoute
  TentangRoute: typeof TentangRoute
  TipsInterviewRoute: typeof TipsInterviewRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAiCvReviewRoute: typeof ApiAiCvReviewRoute
  ApiHeadersCheckRoute: typeof ApiHeadersCheckRoute
  ManifestWebmanifestRoute: typeof ManifestWebmanifestRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SecurityTxtRoute: typeof SecurityTxtRoute
  ShareTokenRoute: typeof ShareTokenRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips-interview': {
      id: '/tips-interview'
      path: '/tips-interview'
      fullPath: '/tips-interview'
      preLoaderRoute: typeof TipsInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template': {
      id: '/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-ketentuan': {
      id: '/syarat-ketentuan'
      path: '/syarat-ketentuan'
      fullPath: '/syarat-ketentuan'
      preLoaderRoute: typeof SyaratKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-coaching': {
      id: '/private-coaching'
      path: '/private-coaching'
      fullPath: '/private-coaching'
      preLoaderRoute: typeof PrivateCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan-cv-ats': {
      id: '/panduan-cv-ats'
      path: '/panduan-cv-ats'
      fullPath: '/panduan-cv-ats'
      preLoaderRoute: typeof PanduanCvAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-password': {
      id: '/lupa-password'
      path: '/lupa-password'
      fullPath: '/lupa-password'
      preLoaderRoute: typeof LupaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lowongan': {
      id: '/lowongan'
      path: '/lowongan'
      fullPath: '/lowongan'
      preLoaderRoute: typeof LowonganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harga': {
      id: '/harga'
      path: '/harga'
      fullPath: '/harga'
      preLoaderRoute: typeof HargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitur': {
      id: '/fitur'
      path: '/fitur'
      fullPath: '/fitur'
      preLoaderRoute: typeof FiturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips-interview/$slug': {
      id: '/tips-interview/$slug'
      path: '/$slug'
      fullPath: '/tips-interview/$slug'
      preLoaderRoute: typeof TipsInterviewSlugRouteImport
      parentRoute: typeof TipsInterviewRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/txt': {
      id: '/security/txt'
      path: '/security/txt'
      fullPath: '/security/txt'
      preLoaderRoute: typeof SecurityTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest/webmanifest': {
      id: '/manifest/webmanifest'
      path: '/manifest/webmanifest'
      fullPath: '/manifest/webmanifest'
      preLoaderRoute: typeof ManifestWebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lowongan/$slug': {
      id: '/lowongan/$slug'
      path: '/$slug'
      fullPath: '/lowongan/$slug'
      preLoaderRoute: typeof LowonganSlugRouteImport
      parentRoute: typeof LowonganRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/headers-check': {
      id: '/api/headers-check'
      path: '/api/headers-check'
      fullPath: '/api/headers-check'
      preLoaderRoute: typeof ApiHeadersCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-cv-review': {
      id: '/api/ai-cv-review'
      path: '/api/ai-cv-review'
      fullPath: '/api/ai-cv-review'
      preLoaderRoute: typeof ApiAiCvReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulasi-wawancara': {
      id: '/_authenticated/simulasi-wawancara'
      path: '/simulasi-wawancara'
      fullPath: '/simulasi-wawancara'
      preLoaderRoute: typeof AuthenticatedSimulasiWawancaraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lamaran': {
      id: '/_authenticated/lamaran'
      path: '/lamaran'
      fullPath: '/lamaran'
      preLoaderRoute: typeof AuthenticatedLamaranRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analitik': {
      id: '/_authenticated/analitik'
      path: '/analitik'
      fullPath: '/analitik'
      preLoaderRoute: typeof AuthenticatedAnalitikRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/akun': {
      id: '/_authenticated/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AuthenticatedAkunRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthenticatedToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cv/': {
      id: '/_authenticated/cv/'
      path: '/cv'
      fullPath: '/cv/'
      preLoaderRoute: typeof AuthenticatedCvIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cv-review/': {
      id: '/_authenticated/cv-review/'
      path: '/cv-review'
      fullPath: '/cv-review/'
      preLoaderRoute: typeof AuthenticatedCvReviewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/simulasi-wawancara/$id': {
      id: '/_authenticated/simulasi-wawancara/$id'
      path: '/$id'
      fullPath: '/simulasi-wawancara/$id'
      preLoaderRoute: typeof AuthenticatedSimulasiWawancaraIdRouteImport
      parentRoute: typeof AuthenticatedSimulasiWawancaraRoute
    }
    '/_authenticated/score/$cvId': {
      id: '/_authenticated/score/$cvId'
      path: '/score/$cvId'
      fullPath: '/score/$cvId'
      preLoaderRoute: typeof AuthenticatedScoreCvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cv/$id': {
      id: '/_authenticated/cv/$id'
      path: '/cv/$id'
      fullPath: '/cv/$id'
      preLoaderRoute: typeof AuthenticatedCvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cv-review/$cvId': {
      id: '/_authenticated/cv-review/$cvId'
      path: '/cv-review/$cvId'
      fullPath: '/cv-review/$cvId'
      preLoaderRoute: typeof AuthenticatedCvReviewCvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/tools/keyword/$cvId': {
      id: '/_authenticated/tools/keyword/$cvId'
      path: '/tools/keyword/$cvId'
      fullPath: '/tools/keyword/$cvId'
      preLoaderRoute: typeof AuthenticatedToolsKeywordCvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/cover-letter/$cvId': {
      id: '/_authenticated/tools/cover-letter/$cvId'
      path: '/tools/cover-letter/$cvId'
      fullPath: '/tools/cover-letter/$cvId'
      preLoaderRoute: typeof AuthenticatedToolsCoverLetterCvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSimulasiWawancaraRouteChildren {
  AuthenticatedSimulasiWawancaraIdRoute: typeof AuthenticatedSimulasiWawancaraIdRoute
}

const AuthenticatedSimulasiWawancaraRouteChildren: AuthenticatedSimulasiWawancaraRouteChildren =
  {
    AuthenticatedSimulasiWawancaraIdRoute:
      AuthenticatedSimulasiWawancaraIdRoute,
  }

const AuthenticatedSimulasiWawancaraRouteWithChildren =
  AuthenticatedSimulasiWawancaraRoute._addFileChildren(
    AuthenticatedSimulasiWawancaraRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAkunRoute: typeof AuthenticatedAkunRoute
  AuthenticatedAnalitikRoute: typeof AuthenticatedAnalitikRoute
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLamaranRoute: typeof AuthenticatedLamaranRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedSimulasiWawancaraRoute: typeof AuthenticatedSimulasiWawancaraRouteWithChildren
  AuthenticatedCvReviewCvIdRoute: typeof AuthenticatedCvReviewCvIdRoute
  AuthenticatedCvIdRoute: typeof AuthenticatedCvIdRoute
  AuthenticatedScoreCvIdRoute: typeof AuthenticatedScoreCvIdRoute
  AuthenticatedCvReviewIndexRoute: typeof AuthenticatedCvReviewIndexRoute
  AuthenticatedCvIndexRoute: typeof AuthenticatedCvIndexRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
  AuthenticatedToolsCoverLetterCvIdRoute: typeof AuthenticatedToolsCoverLetterCvIdRoute
  AuthenticatedToolsKeywordCvIdRoute: typeof AuthenticatedToolsKeywordCvIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAkunRoute: AuthenticatedAkunRoute,
  AuthenticatedAnalitikRoute: AuthenticatedAnalitikRoute,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLamaranRoute: AuthenticatedLamaranRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedSimulasiWawancaraRoute:
    AuthenticatedSimulasiWawancaraRouteWithChildren,
  AuthenticatedCvReviewCvIdRoute: AuthenticatedCvReviewCvIdRoute,
  AuthenticatedCvIdRoute: AuthenticatedCvIdRoute,
  AuthenticatedScoreCvIdRoute: AuthenticatedScoreCvIdRoute,
  AuthenticatedCvReviewIndexRoute: AuthenticatedCvReviewIndexRoute,
  AuthenticatedCvIndexRoute: AuthenticatedCvIndexRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
  AuthenticatedToolsCoverLetterCvIdRoute:
    AuthenticatedToolsCoverLetterCvIdRoute,
  AuthenticatedToolsKeywordCvIdRoute: AuthenticatedToolsKeywordCvIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface LowonganRouteChildren {
  LowonganSlugRoute: typeof LowonganSlugRoute
}

const LowonganRouteChildren: LowonganRouteChildren = {
  LowonganSlugRoute: LowonganSlugRoute,
}

const LowonganRouteWithChildren = LowonganRoute._addFileChildren(
  LowonganRouteChildren,
)

interface TipsInterviewRouteChildren {
  TipsInterviewSlugRoute: typeof TipsInterviewSlugRoute
}

const TipsInterviewRouteChildren: TipsInterviewRouteChildren = {
  TipsInterviewSlugRoute: TipsInterviewSlugRoute,
}

const TipsInterviewRouteWithChildren = TipsInterviewRoute._addFileChildren(
  TipsInterviewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  FiturRoute: FiturRoute,
  HargaRoute: HargaRoute,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  KontakRoute: KontakRoute,
  LoginRoute: LoginRoute,
  LowonganRoute: LowonganRouteWithChildren,
  LupaPasswordRoute: LupaPasswordRoute,
  PanduanCvAtsRoute: PanduanCvAtsRoute,
  PrivateCoachingRoute: PrivateCoachingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SyaratKetentuanRoute: SyaratKetentuanRoute,
  TemplateRoute: TemplateRoute,
  TentangRoute: TentangRoute,
  TipsInterviewRoute: TipsInterviewRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAiCvReviewRoute: ApiAiCvReviewRoute,
  ApiHeadersCheckRoute: ApiHeadersCheckRoute,
  ManifestWebmanifestRoute: ManifestWebmanifestRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SecurityTxtRoute: SecurityTxtRoute,
  ShareTokenRoute: ShareTokenRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
