-- Seed: 110 sample soal Tryout SKD (TWK:30, TIU:35, TKP:45)
-- Soal bersumber dari bank latihan umum dan disusun untuk contoh.
-- Setiap soal sudah sesuai dengan format pilihan ganda A/B/C/D/E.

DO $$
DECLARE
  v_set_id UUID;
BEGIN
  SELECT id INTO v_set_id FROM public.tryout_exam_sets WHERE slug = 'cpns-skd-set-1';
  IF v_set_id IS NULL THEN
    RAISE EXCEPTION 'Exam set cpns-skd-set-1 belum ada. Jalankan migration sebelumnya.';
  END IF;

  -- Hapus soal lama jika ada (untuk re-seed idempotent)
  DELETE FROM public.tryout_questions WHERE exam_set_id = v_set_id;

  -- ═════════════════════════════════════════════════════════════════════════
  -- TWK (Tes Wawasan Kebangsaan) — 30 soal
  -- ═════════════════════════════════════════════════════════════════════════
  INSERT INTO public.tryout_questions (exam_set_id, subtest, question_number, question_text, options, correct_answer, explanation, category, difficulty) VALUES
  (v_set_id, 'twk', 1,
    'Pancasila sebagai dasar negara Indonesia secara konstitusional tercantum dalam...',
    '[{"key":"A","text":"Pembukaan UUD 1945 Alinea I"},{"key":"B","text":"Pembukaan UUD 1945 Alinea IV"},{"key":"C","text":"Batang Tubuh UUD 1945"},{"key":"D","text":"Penjelasan UUD 1945"},{"key":"E","text":"TAP MPR No. XVIII/MPR/1998"}]'::jsonb,
    'B', 'Pancasila sebagai dasar negara tercantum dalam Pembukaan UUD 1945 Alinea IV.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 2,
    'Rumusan Pancasila yang sah dan benar terdapat pada...',
    '[{"key":"A","text":"Pidato Bung Karno tanggal 1 Juni 1945"},{"key":"B","text":"Piagam Jakarta tanggal 22 Juni 1945"},{"key":"C","text":"Maklumat Wakil Presiden No. X"},{"key":"D","text":"Pembukaan UUD 1945"},{"key":"E","text":"Keputusan Presiden No. 12 Tahun 1968"}]'::jsonb,
    'D', 'Rumusan final dan sah Pancasila tercantum dalam Pembukaan UUD 1945.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 3,
    'Sila pertama Pancasila "Ketuhanan Yang Maha Esa" mengandung makna bahwa negara...',
    '[{"key":"A","text":"Menetapkan satu agama resmi"},{"key":"B","text":"Melarang kegiatan agama"},{"key":"C","text":"Menjamin kebebasan beragama"},{"key":"D","text":"Mengatur tempat ibadah"},{"key":"E","text":"Mensubsidi agama tertentu"}]'::jsonb,
    'C', 'Sila pertama menjamin kebebasan setiap warga untuk memeluk agama dan beribadah sesuai keyakinannya.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 4,
    'BPUPKI dibentuk pada tanggal...',
    '[{"key":"A","text":"1 Maret 1945"},{"key":"B","text":"29 April 1945"},{"key":"C","text":"1 Juni 1945"},{"key":"D","text":"17 Agustus 1945"},{"key":"E","text":"18 Agustus 1945"}]'::jsonb,
    'B', 'BPUPKI (Badan Penyelidik Usaha-Usaha Persiapan Kemerdekaan Indonesia) dibentuk pada 29 April 1945.', 'Sejarah', 'medium'),
  (v_set_id, 'twk', 5,
    'Tujuan negara Indonesia tercantum dalam Pembukaan UUD 1945 Alinea...',
    '[{"key":"A","text":"I"},{"key":"B","text":"II"},{"key":"C","text":"III"},{"key":"D","text":"IV"},{"key":"E","text":"V"}]'::jsonb,
    'D', 'Tujuan negara Indonesia (melindungi segenap bangsa, mencerdaskan kehidupan, dst.) tercantum dalam Pembukaan UUD 1945 Alinea IV.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 6,
    'Lembaga negara yang berwenang mengubah UUD 1945 adalah...',
    '[{"key":"A","text":"DPR"},{"key":"B","text":"Presiden"},{"key":"C","text":"MPR"},{"key":"D","text":"MA"},{"key":"E","text":"MK"}]'::jsonb,
    'C', 'Sesuai Pasal 3 UUD 1945, MPR berwenang mengubah dan menetapkan UUD.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 7,
    'Piagam Jakarta (Jakarta Charter) tanggal 22 Juni 1945 dihasilkan oleh...',
    '[{"key":"A","text":"PPKI"},{"key":"B","text":"BPUPKI"},{"key":"C","text":"Panitian Sembilan"},{"key":"D","text":"KNIP"},{"key":"E","text":"KNPI"}]'::jsonb,
    'C', 'Piagam Jakarta disusun oleh Panitia Sembilan yang diketuai Ir. Soekarno.', 'Sejarah', 'medium'),
  (v_set_id, 'twk', 8,
    'Sistem pemerintahan Indonesia menurut UUD 1945 adalah...',
    '[{"key":"A","text":"Presidensial"},{"key":"B","text":"Parlementer"},{"key":"C","text":"Semi-presidensial"},{"key":"D","text":"Monarki konstitusional"},{"key":"E","text":"Federal"}]'::jsonb,
    'A', 'Indonesia menganut sistem pemerintahan presidensial di mana presiden adalah kepala negara sekaligus kepala pemerintahan.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 9,
    'Makna semboyan "Bhinneka Tunggal Ika" adalah...',
    '[{"key":"A","text":"Persatuan dalam perbedaan"},{"key":"B","text":"Persatuan tanpa perbedaan"},{"key":"C","text":"Perbedaan yang harus dihilangkan"},{"key":"D","text":"Persaingan sehat antar suku"},{"key":"E","text":"Toleransi hanya untuk agama tertentu"}]'::jsonb,
    'A', 'Bhinneka Tunggal Ika artinya berbeda-beda tetapi tetap satu, mengakui keberagaman dalam bingkai persatuan.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 10,
    'Proklamasi Kemerdekaan Indonesia dibacakan oleh...',
    '[{"key":"A","text":"Drs. Moh. Hatta"},{"key":"B","text":"Ir. Soekarno"},{"key":"C","text":"Sutan Sjahrir"},{"key":"D","text":"Soepomo"},{"key":"E","text":"Ahmad Soebardjo"}]'::jsonb,
    'B', 'Proklamasi Kemerdekaan Indonesia dibacakan oleh Ir. Soekarno pada 17 Agustus 1945 di Jl. Pegangsaan Timur No. 56, Jakarta.', 'Sejarah', 'easy'),
  (v_set_id, 'twk', 11,
    'Lagu kebangsaan Indonesia Raya diciptakan oleh...',
    '[{"key":"A","text":"W.R. Supratman"},{"key":"B","text":"C. Simanjuntak"},{"key":"C","text":"Kusbini"},{"key":"D","text":"Ismail Marzuki"},{"key":"E","text":"Ibu Sud"}]'::jsonb,
    'A', 'Lagu Indonesia Raya diciptakan oleh Wage Rudolf Supratman dan pertama kali diperkenalkan pada Sumpah Pemuda 1928.', 'Sejarah', 'easy'),
  (v_set_id, 'twk', 12,
    'Hari sumpah pemuda diperingati setiap tanggal...',
    '[{"key":"A","text":"17 Agustus"},{"key":"B","text":"28 Oktober"},{"key":"C","text":"10 November"},{"key":"D","text":"1 Juni"},{"key":"E","text":"22 Juni"}]'::jsonb,
    'B', 'Hari Sumpah Pemuda diperingati setiap tanggal 28 Oktober, ditandai dengan Kongres Pemuda II 1928.', 'Sejarah', 'easy'),
  (v_set_id, 'twk', 13,
    'Fungsi Pancasila sebagai dasar negara adalah...',
    '[{"key":"A","text":"Sumber hukum dan pedoman penyelenggaraan negara"},{"key":"B","text":"Simbol budaya bangsa"},{"key":"C","text":"Identitas negara asing"},{"key":"D","text":"Alat propaganda pemerintah"},{"key":"E","text":"Sumber mata pencaharian"}]'::jsonb,
    'A', 'Pancasila sebagai dasar negara menjadi sumber hukum dan pedoman dalam penyelenggaraan negara.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 14,
    'Sidang pertama BPUPKI dilaksanakan pada tanggal...',
    '[{"key":"A","text":"29 April - 1 Mei 1945"},{"key":"B","text":"10-17 Juni 1945"},{"key":"C","text":"18-22 Juni 1945"},{"key":"D","text":"1-5 Juni 1945"},{"key":"E","text":"14-16 Juni 1945"}]'::jsonb,
    'A', 'Sidang pertama BPUPKI berlangsung 29 April - 1 Mei 1945 membahas dasar negara.', 'Sejarah', 'medium'),
  (v_set_id, 'twk', 15,
    'Tokoh yang mengemukakan lima asas dasar negara Indonesia pada sidang BPUPKI pertama adalah...',
    '[{"key":"A","text":"Moh. Hatta"},{"key":"B","text":"Ir. Soekarno"},{"key":"C","text":"Soepomo"},{"key":"D","text":"Moh. Yamin"},{"key":"E","text":"A.A. Maramis"}]'::jsonb,
    'B', 'Ir. Soekarno mengemukakan Pancasila pada 1 Juni 1945, yang kemudian diperingati sebagai Hari Lahir Pancasila.', 'Sejarah', 'medium'),
  (v_set_id, 'twk', 16,
    'Kedaulatan negara Indonesia berada di tangan rakyat dan dilaksanakan menurut...',
    '[{"key":"A","text":"Kebebasan mutlak rakyat"},{"key":"B","text":"UUD 1945"},{"key":"C","text":"Keputusan presiden"},{"key":"D","text":"Hukum adat"},{"key":"E","text":"Hukum internasional"}]'::jsonb,
    'B', 'Pasal 1 ayat (2) UUD 1945: kedaulatan berada di tangan rakyat dan dilaksanakan menurut UUD.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 17,
    'Bangsa Indonesia memiliki bahasa persatuan yaitu...',
    '[{"key":"A","text":"Bahasa Jawa"},{"key":"B","text":"Bahasa Melayu Pasar"},{"key":"C","text":"Bahasa Indonesia"},{"key":"D","text":"Bahasa Inggris"},{"key":"E","text":"Bahasa Latin"}]'::jsonb,
    'C', 'Bahasa Indonesia ditetapkan sebagai bahasa persatuan dan bahasa negara.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 18,
    'Prinsip dasar demokrasi Pancasila adalah...',
    '[{"key":"A","text":"Demokrasi liberal"},{"key":"B","text":"Demokrasi rakyat"},{"key":"C","text":"Demokrasi terpimpin"},{"key":"D","text":"Demokrasi konstitusional"},{"key":"E","text":"Demokrasi parlementer"}]'::jsonb,
    'B', 'Indonesia menganut demokrasi Pancasila yang merupakan demokrasi rakyat berdasarkan musyawarah mufakat.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 19,
    'Otonomi daerah di Indonesia bertujuan untuk...',
    '[{"key":"A","text":"Memutus hubungan dengan pusat"},{"key":"B","text":"Meningkatkan pelayanan publik dan pemerataan pembangunan"},{"key":"C","text":"Mengurangi peran pemerintah"},{"key":"D","text":"Memperkuat birokrasi pusat"},{"key":"E","text":"Menghilangkan batas wilayah"}]'::jsonb,
    'B', 'Otonomi daerah bertujuan meningkatkan pelayanan publik dan pemerataan pembangunan di seluruh Indonesia.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 20,
    'Lembaga yang berwenang menguji undang-undang terhadap UUD 1945 adalah...',
    '[{"key":"A","text":"Mahkamah Agung"},{"key":"B","text":"Mahkamah Konstitusi"},{"key":"C","text":"DPR"},{"key":"D","text":"Presiden"},{"key":"E","text":"BPK"}]'::jsonb,
    'B', 'Mahkamah Konstitusi (MK) berwenang menguji undang-undang terhadap UUD 1945 (judicial review).', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 21,
    'Sistem pertahanan keamanan rakyat semesta (SISHANTAKAM) menganut prinsip...',
    '[{"key":"A","text":"Militer profesional"},{"key":"B","text":"Pertahanan sipil"},{"key":"C","text":"Wajib militer"},{"key":"D","text":"Pertahanan seluruh rakyat"},{"key":"E","text":"Pertahanan paramiliter"}]'::jsonb,
    'D', 'SISHANTAKAM bermakna bahwa pertahanan dan keamanan adalah tanggung jawab seluruh rakyat.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 22,
    'Pancasila sebagai pandangan hidup bangsa berfungsi sebagai...',
    '[{"key":"A","text":"Petunjuk dalam kehidupan bermasyarakat"},{"key":"B","text":"Sumber hukum formal"},{"key":"C","text":"Alat politik"},{"key":"D","text":"Dokumen sejarah"},{"key":"E","text":"Simbol kenegaraan"}]'::jsonb,
    'A', 'Pancasila sebagai pandangan hidup bangsa berfungsi sebagai petunjuk/pedoman dalam kehidupan bermasyarakat, berbangsa, dan bernegara.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 23,
    'Tujuan akhir dari negara Indonesia menurut UUD 1945 adalah...',
    '[{"key":"A","text":"Menjadi negara maju"},{"key":"B","text":"Mewujudkan masyarakat adil dan makmur"},{"key":"C","text":"Menyatukan seluruh nusantara"},{"key":"D","text":"Menguasai ekonomi dunia"},{"key":"E","text":"Menjadi superpower"}]'::jsonb,
    'B', 'Tujuan akhir negara Indonesia adalah terwujudnya masyarakat yang adil dan makmur berdasarkan Pancasila.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 24,
    'Bhinneka Tunggal Ika tertulis pada lambang negara Garuda Pancasila, tepatnya di...',
    '[{"key":"A","text":"Perisai"},{"key":"B","text":"Cengkeraman"},{"key":"C","text":"Pita yang dicengkeram"},{"key":"D","text":"Bintang"},{"key":"E","text":"Burung Garuda"}]'::jsonb,
    'C', 'Semboyan Bhinneka Tunggal Ika tertulis pada pita yang dicengkeram oleh cakar Garuda Pancasila.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 25,
    'Sila kedua Pancasila "Kemanusiaan yang Adil dan Beradab" bermakna...',
    '[{"key":"A","text":"Menghormati hak asasi manusia"},{"key":"B","text":"Mengutamakan kepentingan pribadi"},{"key":"C","text":"Membedakan derajat manusia"},{"key":"D","text":"Memprioritaskan golongan tertentu"},{"key":"E","text":"Menolak bantuan luar negeri"}]'::jsonb,
    'A', 'Sila kedua menjunjung tinggi nilai kemanusiaan, keadilan, dan penghormatan terhadap HAM.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 26,
    'Irian Barat (Papua) resmi menjadi bagian Indonesia pada...',
    '[{"key":"A","text":"1945"},{"key":"B","text":"1949"},{"key":"C","text":"1950"},{"key":"D","text":"1963"},{"key":"E","text":"1976"}]'::jsonb,
    'D', 'Irian Barat resmi kembali ke pangkuan Indonesia pada 1963 melalui Perjanjian New York.', 'Sejarah', 'medium'),
  (v_set_id, 'twk', 27,
    'TAP MPR No. XXV/MPRS/1966 mengatur tentang...',
    '[{"key":"A","text":"Pembubaran PKI"},{"key":"B","text":"Supersemar"},{"key":"C","text":"Pidato presiden"},{"key":"D","text":"Anggaran negara"},{"key":"E","text":"Sidang kabinet"}]'::jsonb,
    'A', 'TAP MPR No. XXV/MPRS/1966 tentang Pembubaran PKI dan larangan ajaran komunisme.', 'Sejarah', 'hard'),
  (v_set_id, 'twk', 28,
    'Yang bukan merupakan contoh perilaku penerapan sila keempat Pancasila adalah...',
    '[{"key":"A","text":"Musyawarah dalam keluarga"},{"key":"B","text":"Mengutamakan keputusan bersama"},{"key":"C","text":"Diskusi terbuka di lingkungan kerja"},{"key":"D","text":"Memutus sendiri tanpa diskusi"},{"key":"E","text":"Rembug desa untuk kepentingan bersama"}]'::jsonb,
    'D', 'Sila keempat menekankan musyawarah. Memutus sendiri tanpa diskusi bertentangan dengan sila keempat.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 29,
    'Pancasila sebagai ideologi terbuka mengandung makna bahwa...',
    '[{"key":"A","text":"Tidak bisa berubah sama sekali"},{"key":"B","text":"Bersifat kaku dan tertutup"},{"key":"C","text":"Tidak relevan dengan zaman"},{"key":"D","text":"Mampu menyesuaikan diri dengan perkembangan zaman"},{"key":"E","text":"Hanya untuk golongan tertentu"}]'::jsonb,
    'D', 'Pancasila sebagai ideologi terbuka bersifat fleksibel dan mampu beradaptasi dengan perkembangan zaman tanpa kehilangan jati diri.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 30,
    'Yang bukan menjadi bagian dari proklamasi kemerdekaan adalah...',
    '[{"key":"A","text":"Ir. Soekarno"},{"key":"B","text":"Drs. Moh. Hatta"},{"key":"C","text":"Golongan muda"},{"key":"D","text":"PPKI"},{"key":"E","text":"Tuan RADEN SOEKARNO"}]'::jsonb,
    'D', 'PPKI dibentuk setelah proklamasi untuk menyiapkan pemerintahan, bukan penandatangan proklamasi.', 'Sejarah', 'hard');

  -- ═════════════════════════════════════════════════════════════════════════
  -- TIU (Tes Intelegensi Umum) — 35 soal (Verbal, Numerik, Figural, Logis)
  -- ═════════════════════════════════════════════════════════════════════════
  INSERT INTO public.tryout_questions (exam_set_id, subtest, question_number, question_text, options, correct_answer, explanation, category, difficulty) VALUES
  (v_set_id, 'tiu', 31,
    'Jika sebuah persegi panjang memiliki panjang 12 cm dan lebar 8 cm, maka luasnya adalah...',
    '[{"key":"A","text":"40 cm2"},{"key":"B","text":"80 cm2"},{"key":"C","text":"96 cm2"},{"key":"D","text":"100 cm2"},{"key":"E","text":"120 cm2"}]'::jsonb,
    'C', 'Luas persegi panjang = panjang x lebar = 12 x 8 = 96 cm².', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 32,
    'Jika 3, 6, 12, 24, ..., maka angka berikutnya adalah...',
    '[{"key":"A","text":"30"},{"key":"B","text":"36"},{"key":"C","text":"48"},{"key":"D","text":"60"},{"key":"E","text":"96"}]'::jsonb,
    'C', 'Pola deret: setiap angka dikalikan 2. 3×2=6, 6×2=12, 12×2=24, 24×2=48.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 33,
    'Sinonim dari kata "GIGIH" adalah...',
    '[{"key":"A","text":"Malas"},{"key":"B","text":"Tekun"},{"key":"C","text":"Lemah"},{"key":"D","text":"Putus asa"},{"key":"E","text":"Acuh"}]'::jsonb,
    'B', 'Gigih sinonim dengan tekun, ulet, pantang menyerah.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 34,
    'Antonim dari kata "OPTIMIS" adalah...',
    '[{"key":"A","text":"Pesimis"},{"key":"B","text":"Realistis"},{"key":"C","text":"Idealistis"},{"key":"D","text":"Materialistis"},{"key":"E","text":"Praktis"}]'::jsonb,
    'A', 'Antonim dari optimis adalah pesimis.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 35,
    'Jika sebuah kereta melaju dengan kecepatan 80 km/jam selama 2,5 jam, maka jarak yang ditempuh adalah...',
    '[{"key":"A","text":"100 km"},{"key":"B","text":"150 km"},{"key":"C","text":"180 km"},{"key":"D","text":"200 km"},{"key":"E","text":"220 km"}]'::jsonb,
    'D', 'Jarak = kecepatan x waktu = 80 x 2,5 = 200 km.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 36,
    'Semua mamalia memiliki jantung. Paus adalah mamalia. Maka...',
    '[{"key":"A","text":"Paus tidak memiliki jantung"},{"key":"B","text":"Paus memiliki jantung"},{"key":"C","text":"Paus bukan mamalia"},{"key":"D","text":"Semua mamalia adalah paus"},{"key":"E","text":"Tidak dapat disimpulkan"}]'::jsonb,
    'B', 'Karena paus mamalia dan semua mamalia memiliki jantung, maka paus memiliki jantung (silogisme).', 'Logis', 'easy'),
  (v_set_id, 'tiu', 37,
    'Jika harga 5 buku = Rp 75.000, maka harga 1 buku adalah...',
    '[{"key":"A","text":"Rp 10.000"},{"key":"B","text":"Rp 12.000"},{"key":"C","text":"Rp 15.000"},{"key":"D","text":"Rp 18.000"},{"key":"E","text":"Rp 20.000"}]'::jsonb,
    'C', '75.000 / 5 = Rp 15.000 per buku.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 38,
    '12, 14, 16, 20, 22, ... Angka berikutnya adalah...',
    '[{"key":"A","text":"24"},{"key":"B","text":"26"},{"key":"C","text":"28"},{"key":"D","text":"30"},{"key":"E","text":"32"}]'::jsonb,
    'B', 'Pola: tambah 2, tambah 2, tambah 4, tambah 2, tambah 2, tambah 4 → 22 + 4 = 26.', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 39,
    'Pohon : Hutan = Pohon : ...',
    '[{"key":"A","text":"Tanah"},{"key":"B","text":"Akar"},{"key":"C","text":"Daun"},{"key":"D","text":"Kayu"},{"key":"E","text":"Kebun"}]'::jsonb,
    'E', 'Pohon tumbuh banyak di hutan. Analogi: pohon tumbuh banyak di kebun.', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 40,
    'Berapakah 25% dari 240?',
    '[{"key":"A","text":"50"},{"key":"B","text":"60"},{"key":"C","text":"70"},{"key":"D","text":"80"},{"key":"E","text":"100"}]'::jsonb,
    'B', '25% × 240 = (1/4) × 240 = 60.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 41,
    'Sebuah tabung memiliki jari-jari 7 cm dan tinggi 10 cm. Volume tabung tersebut (π = 22/7) adalah...',
    '[{"key":"A","text":"1.400 cm3"},{"key":"B","text":"1.540 cm3"},{"key":"C","text":"1.680 cm3"},{"key":"D","text":"1.720 cm3"},{"key":"E","text":"2.200 cm3"}]'::jsonb,
    'B', 'V = πr²t = (22/7) × 7² × 10 = (22/7) × 49 × 10 = 22 × 70 = 1.540 cm³.', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 42,
    'Kata "KONFLIK" bermakna...',
    '[{"key":"A","text":"Persahabatan"},{"key":"B","text":"Perselisihan"},{"key":"C","text":"Kerukunan"},{"key":"D","text":"Kesepian"},{"key":"E","text":"Keheningan"}]'::jsonb,
    'B', 'Konflik adalah perselisihan atau pertentangan.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 43,
    'Manakah yang bukan bilangan prima?',
    '[{"key":"A","text":"2"},{"key":"B","text":"3"},{"key":"C","text":"5"},{"key":"D","text":"7"},{"key":"E","text":"9"}]'::jsonb,
    'E', '9 bukan bilangan prima karena memiliki lebih dari dua faktor (1, 3, 9).', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 44,
    'Dokter : Pasien = Guru : ...',
    '[{"key":"A","text":"Sekolah"},{"key":"B","text":"Murid"},{"key":"C","text":"Buku"},{"key":"D","text":"Pelajaran"},{"key":"E","text":"Kelas"}]'::jsonb,
    'B', 'Dokter melayani pasien; Guru mengajar murid.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 45,
    'Jika 8 + 4 × 3 - 6 ÷ 2 = ...',
    '[{"key":"A","text":"17"},{"key":"B","text":"19"},{"key":"C","text":"21"},{"key":"D","text":"23"},{"key":"E","text":"25"}]'::jsonb,
    'A', 'Urutan operasi: 4×3=12, 6÷2=3, maka 8+12-3=17.', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 46,
    'Rata-rata dari 8, 12, 14, 16, 20 adalah...',
    '[{"key":"A","text":"12"},{"key":"B","text":"13"},{"key":"C","text":"14"},{"key":"D","text":"15"},{"key":"E","text":"16"}]'::jsonb,
    'C', 'Jumlah = 8+12+14+16+20 = 70. Rata-rata = 70/5 = 14.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 47,
    'Semua guru adalah pendidik. Sebagian pendidik adalah penulis. Maka...',
    '[{"key":"A","text":"Semua guru adalah penulis"},{"key":"B","text":"Sebagian guru kemungkinan penulis"},{"key":"C","text":"Semua penulis adalah guru"},{"key":"D","text":"Tidak ada guru yang menulis"},{"key":"E","text":"Tidak ada penulis yang pendidik"}]'::jsonb,
    'B', 'Sebagian guru mungkin juga penulis, tapi tidak semua (karena hanya sebagian pendidik yang penulis).', 'Logis', 'medium'),
  (v_set_id, 'tiu', 48,
    'Berapakah FPB dari 36 dan 48?',
    '[{"key":"A","text":"6"},{"key":"B","text":"8"},{"key":"C","text":"12"},{"key":"D","text":"16"},{"key":"E","text":"24"}]'::jsonb,
    'C', 'FPB 36 dan 48 = 12 (36=2²×3², 48=2⁴×3, irisan = 2²×3=12).', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 49,
    'Antonim dari "PRODUKTIF" adalah...',
    '[{"key":"A","text":"Aktif"},{"key":"B","text":"Rajin"},{"key":"C","text":"Malas"},{"key":"D","text":"Kreatif"},{"key":"E","text":"Inovatif"}]'::jsonb,
    'C', 'Antonim produktif adalah malas.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 50,
    'Jika sebuah mobil menempuh 240 km dengan 20 liter bensin, maka konsumsi BBM per liter adalah...',
    '[{"key":"A","text":"8 km/liter"},{"key":"B","text":"10 km/liter"},{"key":"C","text":"12 km/liter"},{"key":"D","text":"14 km/liter"},{"key":"E","text":"16 km/liter"}]'::jsonb,
    'C', 'Konsumsi = 240 km / 20 liter = 12 km/liter.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 51,
    'Pena : Tinta = Lampu : ...',
    '[{"key":"A","text":"Cahaya"},{"key":"B","text":"Minyak"},{"key":"C","text":"Listrik"},{"key":"D","text":"Api"},{"key":"E","text":"Baterai"}]'::jsonb,
    'C', 'Pena butuh tinta untuk menulis; Lampu butuh listrik untuk menyala.', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 52,
    '1, 4, 9, 16, 25, ... Angka berikutnya adalah...',
    '[{"key":"A","text":"30"},{"key":"B","text":"36"},{"key":"C","text":"40"},{"key":"D","text":"49"},{"key":"E","text":"64"}]'::jsonb,
    'B', 'Pola bilangan kuadrat: 1², 2², 3², 4², 5², 6²=36.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 53,
    'Sinonim kata "INSOMNIA" adalah...',
    '[{"key":"A","text":"Tidur"},{"key":"B","text":"Susah tidur"},{"key":"C","text":"Mimpi indah"},{"key":"D","text":"Ngantuk"},{"key":"E","text":"Kelelahan"}]'::jsonb,
    'B', 'Insomnia adalah gangguan susah tidur.', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 54,
    'Berapa persen dari 0,25?',
    '[{"key":"A","text":"0,25%"},{"key":"B","text":"2,5%"},{"key":"C","text":"25%"},{"key":"D","text":"250%"},{"key":"E","text":"2.500%"}]'::jsonb,
    'C', '0,25 = 25/100 = 25%.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 55,
    'Seekor katak melompat dari titik 0. Lompat pertama ke +5, kedua ke +3, ketiga ke -2, keempat ke -4. Posisi katak sekarang adalah...',
    '[{"key":"A","text":"-2"},{"key":"B","text":"0"},{"key":"C","text":"+2"},{"key":"D","text":"+4"},{"key":"E","text":"+6"}]'::jsonb,
    'C', '0 + 5 + 3 - 2 - 4 = +2.', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 56,
    'Bentuk sederhana dari 24/36 adalah...',
    '[{"key":"A","text":"1/2"},{"key":"B","text":"2/3"},{"key":"C","text":"3/4"},{"key":"D","text":"4/5"},{"key":"E","text":"5/6"}]'::jsonb,
    'B', 'FPB 24 dan 36 = 12, maka 24/12 : 36/12 = 2/3.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 57,
    'Hubungan khusus: MATA : MELIHAT = TELINGA : ...',
    '[{"key":"A","text":"Mendengar"},{"key":"B","text":"Membau"},{"key":"C","text":"Merasakan"},{"key":"D","text":"Mengecap"},{"key":"E","text":"Berbicara"}]'::jsonb,
    'A', 'Mata untuk melihat; Telinga untuk mendengar.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 58,
    'Jika x + y = 12 dan x - y = 4, maka x = ...',
    '[{"key":"A","text":"4"},{"key":"B","text":"6"},{"key":"C","text":"8"},{"key":"D","text":"10"},{"key":"E","text":"12"}]'::jsonb,
    'C', 'Tambah kedua persamaan: 2x = 16, maka x = 8.', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 59,
    'Antonim kata "EGOIS" adalah...',
    '[{"key":"A","text":"Individualis"},{"key":"B","text":"Altruis"},{"key":"C","text":"Materialis"},{"key":"D","text":"Konsumtif"},{"key":"E","text":"Pragmatis"}]'::jsonb,
    'B', 'Antonim egois adalah altruis (mementingkan orang lain).', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 60,
    'Volume kubus dengan panjang sisi 5 cm adalah...',
    '[{"key":"A","text":"25 cm3"},{"key":"B","text":"75 cm3"},{"key":"C","text":"100 cm3"},{"key":"D","text":"125 cm3"},{"key":"E","text":"150 cm3"}]'::jsonb,
    'D', 'V kubus = s³ = 5³ = 125 cm³.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 61,
    'Hewan : Veterinarian = Tanaman : ...',
    '[{"key":"A","text":"Petani"},{"key":"B","text":"Agronom"},{"key":"C","text":"Insinyur"},{"key":"D","text":"Arsitek"},{"key":"E","text":"Dokter"}]'::jsonb,
    'B', 'Hewan ditangani dokter hewan (veterinarian); Tanaman ditangani ahli pertanian/agronom.', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 62,
    '4, 9, 16, 25, ... Angka berikutnya adalah...',
    '[{"key":"A","text":"30"},{"key":"B","text":"36"},{"key":"C","text":"40"},{"key":"D","text":"49"},{"key":"E","text":"64"}]'::jsonb,
    'B', 'Pola kuadrat: 2², 3², 4², 5², 6²=36.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 63,
    'Hasil dari 0,75 × 0,2 adalah...',
    '[{"key":"A","text":"0,015"},{"key":"B","text":"0,15"},{"key":"C","text":"1,5"},{"key":"D","text":"15"},{"key":"E","text":"150"}]'::jsonb,
    'B', '0,75 × 0,2 = 0,15.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 64,
    'Kalimat "Saya memasak nasi goreng" yang setara dengan kalimat pasif adalah...',
    '[{"key":"A","text":"Nasi goreng dimasak oleh saya"},{"key":"B","text":"Saya dimasak nasi goreng"},{"key":"C","text":"Nasi goreng memasak saya"},{"key":"D","text":"Saya memasak nasi goreng (sama)"},{"key":"E","text":"Nasi goreng saya masak"}]'::jsonb,
    'A', 'Bentuk pasif: "Nasi goreng dimasak oleh saya".', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 65,
    'Jika 3 orang dapat menyelesaikan pekerjaan dalam 12 hari, maka 6 orang dapat menyelesaikan dalam...',
    '[{"key":"A","text":"4 hari"},{"key":"B","text":"6 hari"},{"key":"C","text":"8 hari"},{"key":"D","text":"10 hari"},{"key":"E","text":"24 hari"}]'::jsonb,
    'B', 'Berbanding terbalik: 3 × 12 = 6 × x, maka x = 6 hari.', 'Numerik', 'medium');

  -- ═════════════════════════════════════════════════════════════════════════
  -- TKP (Tes Karakteristik Pribadi) — 45 soal
  -- ═════════════════════════════════════════════════════════════════════════
  INSERT INTO public.tryout_questions (exam_set_id, subtest, question_number, question_text, options, scores, explanation, category, difficulty) VALUES
  (v_set_id, 'tkp', 66,
    'Anda diminta menyelesaikan tugas mendadak yang mendesak. Apa yang Anda lakukan?',
    '[{"key":"A","text":"Langsung mengerjakan dengan prioritas utama"},{"key":"B","text":"Berdiskusi dulu dengan rekan"},{"key":"C","text":"Menunggu instruksi atasan lebih lanjut"},{"key":"D","text":"Mendelegasikan ke rekan kerja"},{"key":"E","text":"Meminta penundaan karena tidak sempat"}]'::jsonb,
    '{"A":5,"B":4,"C":2,"D":3,"E":1}'::jsonb,
    'Tugas mendesak menunjukkan prioritas; mengerjakannya langsung menunjukkan inisiatif dan tanggung jawab.',
    'Pelayanan Publik', 'medium'),
  (v_set_id, 'tkp', 67,
    'Rekan kerja Anda melakukan kesalahan yang merugikan tim. Apa sikap Anda?',
    '[{"key":"A","text":"Melaporkan langsung ke atasan"},{"key":"B","text":"Menyampaikan secara pribadi untuk perbaikan"},{"key":"C","text":"Membiarkan saja karena bukan urusan"},{"key":"D","text":"Menyebarkan agar semua tahu"},{"key":"E","text":"Menyalahkan rekan di depan umum"}]'::jsonb,
    '{"A":3,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Pendekatan paling bijak: sampaikan secara pribadi untuk perbaikan tanpa mempermalukan di depan umum.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 68,
    'Anda mendapatkan tugas baru yang belum pernah Anda kuasai. Sikap Anda...',
    '[{"key":"A","text":"Menolak karena tidak mampu"},{"key":"B","text":"Menerima dengan senang hati dan belajar"},{"key":"C","text":"Menerima tapi setengah hati"},{"key":"D","text":"Menyerahkan ke orang lain"},{"key":"E","text":"Menunggu arahan detail dari atasan"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":2}'::jsonb,
    'Inisiatif belajar dan berkembang adalah ciri profesional yang adaptif.',
    'Profesionalisme', 'easy'),
  (v_set_id, 'tkp', 69,
    'Warga datang dengan keluhan yang sangat emosional. Apa yang Anda lakukan?',
    '[{"key":"A","text":"Memotong pembicaraan untuk efisiensi"},{"key":"B","text":"Mendengarkan dengan empati dan mencari solusi"},{"key":"C","text":"Meminta warga lain yang lebih sabar"},{"key":"D","text":"Mengarahkan ke bagian lain tanpa solusi"},{"key":"E","text":"Meninggalkan ruangan karena tidak nyaman"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Pelayanan publik yang baik membutuhkan empati, mendengar, lalu bertindak untuk solusi.',
    'Pelayanan Publik', 'easy'),
  (v_set_id, 'tkp', 70,
    'Tim Anda gagal mencapai target. Sikap Anda sebagai anggota tim...',
    '[{"key":"A","text":"Menyalahkan anggota tertentu"},{"key":"B","text":"Menganalisa penyebab dan belajar bersama"},{"key":"C","text":"Diam saja dan menunggu"},{"key":"D","text":"Mengundurkan diri dari tim"},{"key":"E","text":"Menyalahkan atasan"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Budaya belajar dari kegagalan dan kolaborasi untuk perbaikan mencerminkan profesionalisme.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 71,
    'Atasan memberikan instruksi yang menurut Anda kurang tepat. Anda akan...',
    '[{"key":"A","text":"Langsung menolak"},{"key":"B","text":"Mengerjakan sambil memberi masukan sopan"},{"key":"C","text":"Menggerutu tapi tetap mengerjakan"},{"key":"D","text":"Tidak mengerjakan"},{"key":"E","text":"Melapor ke atasan yang lebih tinggi"}]'::jsonb,
    '{"A":2,"B":5,"C":2,"D":1,"E":2}'::jsonb,
    'Disiplin pada instruksi atasan sambil tetap memberi masukan yang konstruktif adalah sikap dewasa.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 72,
    'Anda memiliki kesempatan untuk promosi jabatan. Rekan kerja Anda juga menginginkan posisi yang sama. Sikap Anda...',
    '[{"key":"A","text":"Bersaing secara sehat dan sportif"},{"key":"B","text":"Menjatuhkan rekan kerja"},{"key":"C","text":"Mundur untuk menghindari konflik"},{"key":"D","text":"Melobi atasan agar dipilih"},{"key":"E","text":"Menyebarkan berita negatif tentang rekan"}]'::jsonb,
    '{"A":5,"B":1,"C":2,"D":1,"E":1}'::jsonb,
    'Kompetisi sehat dan sportif mencerminkan profesionalisme. Menjatuhkan rekan bertentangan dengan etika.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 73,
    'Anda bekerja dalam tim multibudaya. Cara terbaik berkomunikasi adalah...',
    '[{"key":"A","text":"Memaksakan budaya mayoritas"},{"key":"B","text":"Menghormati perbedaan dan mencari kesamaan"},{"key":"C","text":"Menghindari topik sensitif"},{"key":"D","text":"Memisahkan kelompok"},{"key":"E","text":"Meniru cara berkomunikasi satu budaya"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":2}'::jsonb,
    'Menghormati keberagaman budaya dan mencari kesamaan adalah sikap inklusif yang ideal.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 74,
    'Anda melihat atasan Anda bersikap tidak adil kepada bawahan. Sikap Anda...',
    '[{"key":"A","text":"Diam saja karena takut"},{"key":"B","text":"Menyampaikan kepedulian dengan cara yang tepat"},{"key":"C","text":"Mengeluh ke sesama bawahan"},{"key":"D","text":"Melapor ke inspektorat"},{"key":"E","text":"Memancing konflik di kantor"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":3,"E":1}'::jsonb,
    'Menyampaikan kepedulian secara privat dan konstruktif adalah integritas moral yang penting.',
    'Profesionalisme', 'hard'),
  (v_set_id, 'tkp', 75,
    'Anda memiliki ide brilian untuk meningkatkan layanan. Tindakan Anda...',
    '[{"key":"A","text":"Menyimpan ide untuk diri sendiri"},{"key":"B","text":"Menyampaikan ke atasan dengan data pendukung"},{"key":"C","text":"Menunggu sampai ada perintah"},{"key":"D","text":"Menerapkan sendiri tanpa izin"},{"key":"E","text":"Menjual ide ke pihak luar"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Menyampaikan ide melalui jalur resmi dengan data adalah cara profesional menyumbang inovasi.',
    'Pelayanan Publik', 'medium'),
  (v_set_id, 'tkp', 76,
    'Bawahan Anda melakukan kesalahan berulang meski sudah ditegur. Sikap Anda...',
    '[{"key":"A","text":"Memecat langsung"},{"key":"B","text":"Membimbing dengan sabar dan coaching"},{"key":"C","text":"Mengeluh ke atasan"},{"key":"D","text":"Membiarkan saja"},{"key":"E","text":"Membentak di depan umum"}]'::jsonb,
    '{"A":2,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Fungsi manager adalah mengembangkan bawahan; coaching adalah pendekatan kepemimpinan modern.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 77,
    'Warga mengeluh tentang layanan yang lambat. Sebagai petugas, Anda akan...',
    '[{"key":"A","text":"Berdalih bahwa semua juga lambat"},{"key":"B","text":"Meminta maaf dan berusaha mempercepat"},{"key":"C","text":"Menyalahkan sistem"},{"key":"D","text":"Meminta warga menunggu lebih lama"},{"key":"E","text":"Meninggalkan loket"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Pelayanan publik yang prima dimulai dari sikap peduli, minta maaf, dan bertindak cepat.',
    'Pelayanan Publik', 'easy'),
  (v_set_id, 'tkp', 78,
    'Anda diminta memimpin rapat. Gaya kepemimpinan Anda...',
    '[{"key":"A","text":"Mengarahkan tanpa mendengar"},{"key":"B","text":"Memfasilitasi diskusi terbuka"},{"key":"C","text":"Mendominasi pembicaraan"},{"key":"D","text":"Mendelegasikan ke orang lain"},{"key":"E","text":"Memutus tanpa pertimbangan"}]'::jsonb,
    '{"A":2,"B":5,"C":2,"D":3,"E":1}'::jsonb,
    'Kepemimpinan kolaboratif yang memfasilitasi diskusi menghasilkan keputusan lebih baik.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 79,
    'Anda menerima tugas yang tidak sesuai job description. Sikap Anda...',
    '[{"key":"A","text":"Menolak mentah-mentah"},{"key":"B","text":"Menerima dengan bijaksana jika mampu"},{"key":"C","text":"Menolak dengan alasan sibuk"},{"key":"D","text":"Mengerjakan sambil menggerutu"},{"key":"E","text":"Melapor ke serikat pekerja"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":2}'::jsonb,
    'Profesional yang adaptif menerima tantangan baru selama masih dalam kapasitas yang wajar.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 80,
    'Anda ditunjuk mewakili kantor dalam sebuah forum penting. Persiapan Anda...',
    '[{"key":"A","text":"Datang tanpa persiapan"},{"key":"B","text":"Mempersiapkan materi dengan matang"},{"key":"C","text":"Menyalin materi rekan"},{"key":"D","text":"Meminta bahan dari atasan"},{"key":"E","text":"Meminta digantikan orang lain"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":2,"E":1}'::jsonb,
    'Tanggung jawab delegasi menuntut persiapan matang demi citra institusi.',
    'Profesionalisme', 'easy'),
  (v_set_id, 'tkp', 81,
    'Rekan kerja Anda membutuhkan bantuan saat Anda juga sibuk. Anda akan...',
    '[{"key":"A","text":"Menolak dengan alasan sibuk"},{"key":"B","text":"Membantu sebisa mungkin sambil menghargai prioritas"},{"key":"C","text":"Meminta bantuan balik"},{"key":"D","text":"Mengabaikan"},{"key":"E","text":"Menyuruh orang lain"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Solidaritas profesional dengan mengelola prioritas adalah ciri kolaborasi sehat.',
    'Jejaring Kerja', 'easy'),
  (v_set_id, 'tkp', 82,
    'Ada perubahan regulasi yang memengaruhi pekerjaan Anda. Sikap Anda...',
    '[{"key":"A","text":"Bersikukuh dengan cara lama"},{"key":"B","text":"Mempelajari dan menyesuaikan diri"},{"key":"C","text":"Mengeluh ke rekan"},{"key":"D","text":"Menolak perubahan"},{"key":"E","text":"Melanggar regulasi"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Adaptasi terhadap perubahan regulasi adalah bagian dari profesionalisme dan akuntabilitas.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 83,
    'Anda melihat同事 (rekan) menerima suap. Anda akan...',
    '[{"key":"A","text":"Ikut menerima"},{"key":"B","text":"Melaporkan ke atasan atau pihak berwenang"},{"key":"C","text":"Diam karena bukan urusan"},{"key":"D","text":"Ikut menikmati"},{"key":"E","text":"Memeras rekan"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Integritas adalah menolak dan melaporkan pelanggaran meskipun sulit.',
    'Integritas', 'medium'),
  (v_set_id, 'tkp', 84,
    'Warga meminta informasi yang menjadi rahasia negara. Anda akan...',
    '[{"key":"A","text":"Memberikan sebagian informasi"},{"key":"B","text":"Menolak dengan penjelasan yang sopan"},{"key":"C","text":"Memberikan seluruh informasi"},{"key":"D","text":"Meminta imbalan"},{"key":"E","text":"Mengarahkan ke sumber lain secara sembarangan"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Penjaga kerahasiaan informasi negara adalah bagian dari tugas aparatur negara.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 85,
    'Anda bekerja di bawah tekanan tinggi dan mendekati deadline. Anda akan...',
    '[{"key":"A","text":"Panik dan tidak fokus"},{"key":"B","text":"Membuat prioritas dan bekerja terstruktur"},{"key":"C","text":"Menyerah dan menunda"},{"key":"D","text":"Menyalahkan rekan"},{"key":"E","text":"Meninggalkan pekerjaan"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Manajemen stres dan kemampuan memprioritaskan adalah kompetensi penting.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 86,
    'Ada konflik internal yang berpotensi memecah tim. Anda akan...',
    '[{"key":"A","text":"Memperkeruh situasi"},{"key":"B","text":"Menjadi mediator netral"},{"key":"C","text":"Memilih salah satu pihak"},{"key":"D","text":"Menghindar"},{"key":"E","text":"Menyebarkan gosip"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Mediasi yang netral menjaga keharmonisan tim dan menunjukkan kedewasaan.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 87,
    'Anda diberikan wewenang lebih dari biasanya. Sikap Anda...',
    '[{"key":"A","text":"Menyalahgunakan wewenang"},{"key":"B","text":"Menggunakan dengan bertanggung jawab"},{"key":"C","text":"Menolak karena tanggung jawab besar"},{"key":"D","text":"Mendelegasikan semua"},{"key":"E","text":"Memamerkan wewenang"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":2,"E":1}'::jsonb,
    'Wewenang harus dijalankan dengan akuntabilitas dan integritas.',
    'Integritas', 'medium'),
  (v_set_id, 'tkp', 88,
    'Anda diminta bekerja lembur yang tidak dibayar. Sikap Anda...',
    '[{"key":"A","text":"Langsung menolak"},{"key":"B","text":"Mendiskusikan kompensasi dengan baik-baik"},{"key":"C","text":"Diam dan mengerjakan dengan menggerutu"},{"key":"D","text":"Mengajak rekan untuk mogok"},{"key":"E","text":"Meninggalkan pekerjaan tepat waktu"}]'::jsonb,
    '{"A":2,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Komunikasi asertif untuk kompensasi yang adil adalah pendekatan dewasa.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 89,
    'Anda memiliki kesempatan untuk mengikuti pelatihan. Sikap Anda...',
    '[{"key":"A","text":"Mengirim orang lain saja"},{"key":"B","text":"Mengikuti dengan antusias"},{"key":"C","text":"Mengikuti jika diperintah"},{"key":"D","text":"Menolak karena repot"},{"key":"E","text":"Mengikuti tetapi tidak fokus"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Pengembangan kompetensi melalui pelatihan adalah investasi karier.',
    'Profesionalisme', 'easy'),
  (v_set_id, 'tkp', 90,
    'Anda melihat pemborosan anggaran di unit kerja. Tindakan Anda...',
    '[{"key":"A","text":"Ikut-ikutan"},{"key":"B","text":"Menyampaikan untuk efisiensi"},{"key":"C","text":"Diam saja"},{"key":"D","text":"Mengambil bagian"},{"key":"E","text":"Mengeluh tanpa bertindak"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Integritas mencakup keberanian menyampaikan untuk kebaikan organisasi.',
    'Integritas', 'medium'),
  (v_set_id, 'tkp', 91,
    'Warga meminta formulir yang tidak sesuai prosedur. Anda akan...',
    '[{"key":"A","text":"Memberikan formulir"},{"key":"B","text":"Menjelaskan prosedur yang benar dengan ramah"},{"key":"C","text":"Memarahi warga"},{"key":"D","text":"Mengabaikan"},{"key":"E","text":"Meminta warga mengurus sendiri"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Mendidik warga tentang prosedur dengan ramah adalah bagian dari pelayanan informatif.',
    'Pelayanan Publik', 'easy'),
  (v_set_id, 'tkp', 92,
    'Anda memiliki pendapat berbeda dengan mayoritas tim. Anda akan...',
    '[{"key":"A","text":"Diam karena takut berbeda"},{"key":"B","text":"Menyampaikan dengan argumentasi yang baik"},{"key":"C","text":"Memaksakan pendapat"},{"key":"D","text":"Menyabotase keputusan tim"},{"key":"E","text":"Mundur dari tim"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Asertivitas dalam menyampaikan pendapat dengan data adalah ciri kepemimpinan.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 93,
    'Anda lelah fisik dan mental setelah bekerja keras. Anda akan...',
    '[{"key":"A","text":"Memaksakan diri bekerja terus"},{"key":"B","text":"Mengambil cuti untuk pemulihan"},{"key":"C","text":"Mengeluh tanpa bertindak"},{"key":"D","text":"Mengurangi kualitas kerja"},{"key":"E","text":"Meninggalkan tugas"}]'::jsonb,
    '{"A":2,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Self-care dan work-life balance penting untuk menjaga kualitas kerja jangka panjang.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 94,
    'Anda diminta memberikan testimoni positif tentang layanan yang sebenarnya bermasalah. Anda akan...',
    '[{"key":"A","text":"Memberikan testimoni palsu"},{"key":"B","text":"Menyampaikan kebenaran secara berimbang"},{"key":"C","text":"Menolak dengan kasar"},{"key":"D","text":"Menghindari pertanyaan"},{"key":"E","text":"Menyesatkan publik"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Kejujuran dan integritas lebih penting daripada tekanan untuk menyenangkan pihak lain.',
    'Integritas', 'medium'),
  (v_set_id, 'tkp', 95,
    'Tim Anda terdiri dari berbagai latar belakang. Anda akan...',
    '[{"key":"A","text":"Memilih anggota yang sependapat"},{"key":"B","text":"Menghargai keragaman dan membangun sinergi"},{"key":"C","text":"Membentuk sub-kelompok"},{"key":"D","text":"Memaksakan keseragaman"},{"key":"E","text":"Memisahkan diri"}]'::jsonb,
    '{"A":2,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Inklusivitas dan sinergi dari keberagaman menghasilkan tim yang lebih kuat.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 96,
    'Anda menerima keluhan berulang dari warga tentang hal yang sama. Sikap Anda...',
    '[{"key":"A","text":"Mengabaikan"},{"key":"B","text":"Menganalisa akar masalah dan mencarikan solusi"},{"key":"C","text":"Menyalahkan warga"},{"key":"D","text":"Memindahkan tanggung jawab"},{"key":"E","text":"Mengeluh ke rekan"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Pendekatan berbasis masalah (problem solving) adalah inti perbaikan layanan publik.',
    'Pelayanan Publik', 'medium'),
  (v_set_id, 'tkp', 97,
    'Anda ditawari proyek sampingan dari rekan yang berbenturan dengan pekerjaan utama. Anda akan...',
    '[{"key":"A","text":"Menerima langsung"},{"key":"B","text":"Menolak karena khawatir benturan kepentingan"},{"key":"C","text":"Menerima jika tertutup"},{"key":"D","text":"Minta persentase besar"},{"key":"E","text":"Mengelak tanpa alasan"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Menghindari benturan kepentingan (conflict of interest) adalah etika profesional.',
    'Integritas', 'hard'),
  (v_set_id, 'tkp', 98,
    'Anda baru pertama kali ditempatkan di unit baru. Tindakan Anda...',
    '[{"key":"A","text":"Langsung menilai unit lama"},{"key":"B","text":"Belajar dan beradaptasi dengan budaya baru"},{"key":"C","text":"Mengeluh ke senior"},{"key":"D","text":"Menunggu instruksi detail"},{"key":"E","text":"Menghindar dari interaksi"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":2,"E":1}'::jsonb,
    'Adaptabilitas dan keterbukaan belajar adalah sikap profesional saat rotasi.',
    'Profesionalisme', 'easy'),
  (v_set_id, 'tkp', 99,
    'Anda menjadi panitia kegiatan besar. Pendekatan Anda...',
    '[{"key":"A","text":"Memimpin dengan mengabaikan masukan"},{"key":"B","text":"Berkoaborasi dengan panitia dan menerima masukan"},{"key":"C","text":"Mendelegasikan semua"},{"key":"D","text":"Memaksakan keinginan sendiri"},{"key":"E","text":"Menghindari keputusan sulit"}]'::jsonb,
    '{"A":2,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Kepemimpinan kolaboratif menghasilkan kegiatan yang lebih berkualitas dan tim yang solid.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 100,
    'Warga sulit memahami informasi yang kompleks. Anda akan...',
    '[{"key":"A","text":"Memaksa warga untuk paham sendiri"},{"key":"B","text":"Menggunakan bahasa sederhana dan peragaan"},{"key":"C","text":"Meninggalkan warga"},{"key":"D","text":"Mengirimkan dokumen saja"},{"key":"E","text":"Meminta warga bertanya ke orang lain"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":2,"E":1}'::jsonb,
    'Komunikasi yang efektif menyesuaikan gaya bahasa dengan kemampuan audiens.',
    'Pelayanan Publik', 'easy'),
  (v_set_id, 'tkp', 101,
    'Anda diminta mewakili tim dalam presentasi, padahal rekan lain lebih kompeten. Anda akan...',
    '[{"key":"A","text":"Menolak tanpa alasan"},{"key":"B","text":"Menerima dan belajar cepat"},{"key":"C","text":"Meminta digantikan"},{"key":"D","text":"Memaksakan presentasi seadanya"},{"key":"E","text":"Meminta ganti rugi"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Tanggung jawab yang diberikan adalah kesempatan untuk berkembang; inisiatif dan adaptasi kunci.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 102,
    'Anda mendapat informasi sensitif tentang rekan kerja. Anda akan...',
    '[{"key":"A","text":"Menyebarkan untuk alasan apa pun"},{"key":"B","text":"Menjaga kerahasiaan dan tidak menyalahgunakan"},{"key":"C","text":"Menggunakan sebagai alat tawar"},{"key":"D","text":"Mengunggah ke media sosial"},{"key":"E","text":"Menyimpan sambil menunggu momen"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Kerahasiaan informasi dan tidak menyalahgunakannya adalah etika dasar.',
    'Integritas', 'medium'),
  (v_set_id, 'tkp', 103,
    'Anda ditugaskan ke daerah terpencil. Sikap Anda...',
    '[{"key":"A","text":"Menolak keras"},{"key":"B","text":"Menerima dengan komitmen untuk mengabdi"},{"key":"C","text":"Meminta jaminan khusus"},{"key":"D","text":"Mengeluh kepada keluarga"},{"key":"E","text":"Meminta pindah sebelum ditempatkan"}]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Semangat pengabdian dan willingness to serve adalah nilai luhur ASN.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 104,
    'Anda ragu dengan keputusan yang diambil atasan. Anda akan...',
    '[{"key":"A","text":"Mengikuti tanpa bertanya"},{"key":"B","text":"Meminta penjelasan lebih lanjut dengan sopan"},{"key":"C","text":"Mengeluh ke rekan"},{"key":"D","text":"Menolak mentah"},{"key":"E","text":"Memanipulasi situasi"}]'::jsonb,
    '{"A":2,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Komunikasi dua arah yang sopan untuk klarifikasi mencerminkan profesionalisme.',
    'Profesionalisme', 'easy'),
  (v_set_id, 'tkp', 105,
    'Warga mengeluh tentang kebijakan baru yang kurang populer. Anda akan...',
    '[{"key":"A","text":"Ikut menyalahkan kebijakan"},{"key":"B","text":"Menjelaskan tujuan dan manfaat kebijakan dengan sabar"},{"key":"C","text":"Memilih menghindari topik"},{"key":"D","text":"Meminta warga mengadu sendiri"},{"key":"E","text":"Mengeluh ke rekan tentang kebijakan"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Sikap proaktif menjelaskan kebijakan menunjukkan peran edukatif aparatur negara.',
    'Pelayanan Publik', 'medium'),
  (v_set_id, 'tkp', 106,
    'Anda dimintai tolong rekan untuk menyelesaikan tugasnya. Anda akan...',
    '[{"key":"A","text":"Menolak langsung"},{"key":"B","text":"Membantu jika masih dalam kapasitas"},{"key":"C","text":"Meminta imbalan"},{"key":"D","text":"Membantu tapi mengabaikan tugas sendiri"},{"key":"E","text":"Menyebarkan ke banyak orang"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Solidaritas profesional dengan tetap memprioritaskan tugas utama.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 107,
    'Anda ditawari promosi dengan syarat melangkahi senior. Anda akan...',
    '[{"key":"A","text":"Menerima untuk карьер"},{"key":"B","text":"Menerima jika itu sah"},{"key":"C","text":"Menolak karena pertimbangan etika tim"},{"key":"D","text":"Melapor ke atasan lain"},{"key":"E","text":"Meminta bonus khusus"}]'::jsonb,
    '{"A":2,"B":3,"C":5,"D":2,"E":1}'::jsonb,
    'Pertimbangan etika dan dampak terhadap keharmonisan tim penting dalam promosi.',
    'Integritas', 'hard'),
  (v_set_id, 'tkp', 108,
    'Anda memiliki tugas rutin yang membosankan. Anda akan...',
    '[{"key":"A","text":"Meninggalkan begitu saja"},{"key":"B","text":"Mencari cara untuk meningkatkan efisiensi"},{"key":"C","text":"Mengeluh setiap hari"},{"key":"D","text":"Meminta tugas baru"},{"key":"E","text":"Menurunkan kualitas"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":2,"E":1}'::jsonb,
    'Inovasi pada tugas rutin menunjukkan ownership dan profesionalisme.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 109,
    'Anda menjadi target bully rekan kerja. Anda akan...',
    '[{"key":"A","text":"Balas membully"},{"key":"B","text":"Melaporkan ke atasan atau HR untuk perlindungan"},{"key":"C","text":"Diam dan menyimpan dendam"},{"key":"D","text":"Menghindari pekerjaan"},{"key":"E","text":"Menyebarkan identitas pelaku"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Mencari perlindungan melalui jalur resmi adalah sikap dewasa dan sehat.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 110,
    'Anda melihat potensi fraud di unit kerja. Anda akan...',
    '[{"key":"A","text":"Ikut terlibat"},{"key":"B","text":"Melaporkan melalui whistle blower system"},{"key":"C","text":"Diam untuk menjaga hubungan"},{"key":"D","text":"Ikut menikmati hasilnya"},{"key":"E","text":"Menyimpan untuk laporan nanti"}]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Integritas berani menolak fraud melalui whistle blower system yang disediakan.',
    'Integritas', 'hard');
END $$;