-- Seed: 110 sample soal Tryout SKD (TWK:30, TIU:35, TKP:45)
-- Soal bersumber dari bank latihan umum dan disusun untuk contoh.
-- Setiap soal sudah sesuai dengan format pilihan ganda A/B/C/D/E.

DO $$
DECLARE
  v_set_id UUID;
BEGIN
  SELECT id INTO v_set_id FROM public.tryout_exam_sets WHERE slug = 'cpns-skd-set-1';
  IF v_set_id IS NULL THEN
    RAISE EXCEPTION 'Exam set cpns-skd-set-1 belum ada. Jalankan migration sebelumnya.';
  END IF;

  -- Hapus soal lama jika ada (untuk re-seed idempotent)
  DELETE FROM public.tryout_questions WHERE exam_set_id = v_set_id;

  -- ═════════════════════════════════════════════════════════════════════════
  -- TWK (Tes Wawasan Kebangsaan) — 30 soal
  -- ═════════════════════════════════════════════════════════════════════════
  INSERT INTO public.tryout_questions (exam_set_id, subtest, question_number, question_text, options, correct_answer, explanation, category, difficulty) VALUES
  (v_set_id, 'twk', 1,
    'Pancasila sebagai dasar negara Indonesia secara konstitusional tercantum dalam...',
    '["A. Pembukaan UUD 1945 Alinea I","B. Pembukaan UUD 1945 Alinea IV","C. Batang Tubuh UUD 1945","D. Penjelasan UUD 1945","E. TAP MPR No. XVIII/MPR/1998"]'::jsonb,
    'B', 'Pancasila sebagai dasar negara tercantum dalam Pembukaan UUD 1945 Alinea IV.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 2,
    'Rumusan Pancasila yang sah dan benar terdapat pada...',
    '["A. Pidato Bung Karno tanggal 1 Juni 1945","B. Piagam Jakarta tanggal 22 Juni 1945","C. Maklumat Wakil Presiden No. X","D. Pembukaan UUD 1945","E. Keputusan Presiden No. 12 Tahun 1968"]'::jsonb,
    'D', 'Rumusan final dan sah Pancasila tercantum dalam Pembukaan UUD 1945.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 3,
    'Sila pertama Pancasila "Ketuhanan Yang Maha Esa" mengandung makna bahwa negara...',
    '["A. Menetapkan satu agama resmi","B. Melarang kegiatan agama","C. Menjamin kebebasan beragama","D. Mengatur tempat ibadah","E. Mensubsidi agama tertentu"]'::jsonb,
    'C', 'Sila pertama menjamin kebebasan setiap warga untuk memeluk agama dan beribadah sesuai keyakinannya.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 4,
    'BPUPKI dibentuk pada tanggal...',
    '["A. 1 Maret 1945","B. 29 April 1945","C. 1 Juni 1945","D. 17 Agustus 1945","E. 18 Agustus 1945"]'::jsonb,
    'B', 'BPUPKI (Badan Penyelidik Usaha-Usaha Persiapan Kemerdekaan Indonesia) dibentuk pada 29 April 1945.', 'Sejarah', 'medium'),
  (v_set_id, 'twk', 5,
    'Tujuan negara Indonesia tercantum dalam Pembukaan UUD 1945 Alinea...',
    '["A. I","B. II","C. III","D. IV","E. V"]'::jsonb,
    'D', 'Tujuan negara Indonesia (melindungi segenap bangsa, mencerdaskan kehidupan, dst.) tercantum dalam Pembukaan UUD 1945 Alinea IV.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 6,
    'Lembaga negara yang berwenang mengubah UUD 1945 adalah...',
    '["A. DPR","B. Presiden","C. MPR","D. MA","E. MK"]'::jsonb,
    'C', 'Sesuai Pasal 3 UUD 1945, MPR berwenang mengubah dan menetapkan UUD.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 7,
    'Piagam Jakarta (Jakarta Charter) tanggal 22 Juni 1945 dihasilkan oleh...',
    '["A. PPKI","B. BPUPKI","C. Panitian Sembilan","D. KNIP","E. KNPI"]'::jsonb,
    'C', 'Piagam Jakarta disusun oleh Panitia Sembilan yang diketuai Ir. Soekarno.', 'Sejarah', 'medium'),
  (v_set_id, 'twk', 8,
    'Sistem pemerintahan Indonesia menurut UUD 1945 adalah...',
    '["A. Presidensial","B. Parlementer","C. Semi-presidensial","D. Monarki konstitusional","E. Federal"]'::jsonb,
    'A', 'Indonesia menganut sistem pemerintahan presidensial di mana presiden adalah kepala negara sekaligus kepala pemerintahan.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 9,
    'Makna semboyan "Bhinneka Tunggal Ika" adalah...',
    '["A. Persatuan dalam perbedaan","B. Persatuan tanpa perbedaan","C. Perbedaan yang harus dihilangkan","D. Persaingan sehat antar suku","E. Toleransi hanya untuk agama tertentu"]'::jsonb,
    'A', 'Bhinneka Tunggal Ika artinya berbeda-beda tetapi tetap satu, mengakui keberagaman dalam bingkai persatuan.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 10,
    'Proklamasi Kemerdekaan Indonesia dibacakan oleh...',
    '["A. Drs. Moh. Hatta","B. Ir. Soekarno","C. Sutan Sjahrir","D. Soepomo","E. Ahmad Soebardjo"]'::jsonb,
    'B', 'Proklamasi Kemerdekaan Indonesia dibacakan oleh Ir. Soekarno pada 17 Agustus 1945 di Jl. Pegangsaan Timur No. 56, Jakarta.', 'Sejarah', 'easy'),
  (v_set_id, 'twk', 11,
    'Lagu kebangsaan Indonesia Raya diciptakan oleh...',
    '["A. W.R. Supratman","B. C. Simanjuntak","C. Kusbini","D. Ismail Marzuki","E. Ibu Sud"]'::jsonb,
    'A', 'Lagu Indonesia Raya diciptakan oleh Wage Rudolf Supratman dan pertama kali diperkenalkan pada Sumpah Pemuda 1928.', 'Sejarah', 'easy'),
  (v_set_id, 'twk', 12,
    'Hari sumpah pemuda diperingati setiap tanggal...',
    '["A. 17 Agustus","B. 28 Oktober","C. 10 November","D. 1 Juni","E. 22 Juni"]'::jsonb,
    'B', 'Hari Sumpah Pemuda diperingati setiap tanggal 28 Oktober, ditandai dengan Kongres Pemuda II 1928.', 'Sejarah', 'easy'),
  (v_set_id, 'twk', 13,
    'Fungsi Pancasila sebagai dasar negara adalah...',
    '["A. Sumber hukum dan pedoman penyelenggaraan negara","B. Simbol budaya bangsa","C. Identitas negara asing","D. Alat propaganda pemerintah","E. Sumber mata pencaharian"]'::jsonb,
    'A', 'Pancasila sebagai dasar negara menjadi sumber hukum dan pedoman dalam penyelenggaraan negara.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 14,
    'Sidang pertama BPUPKI dilaksanakan pada tanggal...',
    '["A. 29 April - 1 Mei 1945","B. 10-17 Juni 1945","C. 18-22 Juni 1945","D. 1-5 Juni 1945","E. 14-16 Juni 1945"]'::jsonb,
    'A', 'Sidang pertama BPUPKI berlangsung 29 April - 1 Mei 1945 membahas dasar negara.', 'Sejarah', 'medium'),
  (v_set_id, 'twk', 15,
    'Tokoh yang mengemukakan lima asas dasar negara Indonesia pada sidang BPUPKI pertama adalah...',
    '["A. Moh. Hatta","B. Ir. Soekarno","C. Soepomo","D. Moh. Yamin","E. A.A. Maramis"]'::jsonb,
    'B', 'Ir. Soekarno mengemukakan Pancasila pada 1 Juni 1945, yang kemudian diperingati sebagai Hari Lahir Pancasila.', 'Sejarah', 'medium'),
  (v_set_id, 'twk', 16,
    'Kedaulatan negara Indonesia berada di tangan rakyat dan dilaksanakan menurut...',
    '["A. Kebebasan mutlak rakyat","B. UUD 1945","C. Keputusan presiden","D. Hukum adat","E. Hukum internasional"]'::jsonb,
    'B', 'Pasal 1 ayat (2) UUD 1945: kedaulatan berada di tangan rakyat dan dilaksanakan menurut UUD.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 17,
    'Bangsa Indonesia memiliki bahasa persatuan yaitu...',
    '["A. Bahasa Jawa","B. Bahasa Melayu Pasar","C. Bahasa Indonesia","D. Bahasa Inggris","E. Bahasa Latin"]'::jsonb,
    'C', 'Bahasa Indonesia ditetapkan sebagai bahasa persatuan dan bahasa negara.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 18,
    'Prinsip dasar demokrasi Pancasila adalah...',
    '["A. Demokrasi liberal","B. Demokrasi rakyat","C. Demokrasi terpimpin","D. Demokrasi konstitusional","E. Demokrasi parlementer"]'::jsonb,
    'B', 'Indonesia menganut demokrasi Pancasila yang merupakan demokrasi rakyat berdasarkan musyawarah mufakat.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 19,
    'Otonomi daerah di Indonesia bertujuan untuk...',
    '["A. Memutus hubungan dengan pusat","B. Meningkatkan pelayanan publik dan pemerataan pembangunan","C. Mengurangi peran pemerintah","D. Memperkuat birokrasi pusat","E. Menghilangkan batas wilayah"]'::jsonb,
    'B', 'Otonomi daerah bertujuan meningkatkan pelayanan publik dan pemerataan pembangunan di seluruh Indonesia.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 20,
    'Lembaga yang berwenang menguji undang-undang terhadap UUD 1945 adalah...',
    '["A. Mahkamah Agung","B. Mahkamah Konstitusi","C. DPR","D. Presiden","E. BPK"]'::jsonb,
    'B', 'Mahkamah Konstitusi (MK) berwenang menguji undang-undang terhadap UUD 1945 (judicial review).', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 21,
    'Sistem pertahanan keamanan rakyat semesta (SISHANTAKAM) menganut prinsip...',
    '["A. Militer profesional","B. Pertahanan sipil","C. Wajib militer","D. Pertahanan seluruh rakyat","E. Pertahanan paramiliter"]'::jsonb,
    'D', 'SISHANTAKAM bermakna bahwa pertahanan dan keamanan adalah tanggung jawab seluruh rakyat.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 22,
    'Pancasila sebagai pandangan hidup bangsa berfungsi sebagai...',
    '["A. Petunjuk dalam kehidupan bermasyarakat","B. Sumber hukum formal","C. Alat politik","D. Dokumen sejarah","E. Simbol kenegaraan"]'::jsonb,
    'A', 'Pancasila sebagai pandangan hidup bangsa berfungsi sebagai petunjuk/pedoman dalam kehidupan bermasyarakat, berbangsa, dan bernegara.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 23,
    'Tujuan akhir dari negara Indonesia menurut UUD 1945 adalah...',
    '["A. Menjadi negara maju","B. Mewujudkan masyarakat adil dan makmur","C. Menyatukan seluruh nusantara","D. Menguasai ekonomi dunia","E. Menjadi superpower"]'::jsonb,
    'B', 'Tujuan akhir negara Indonesia adalah terwujudnya masyarakat yang adil dan makmur berdasarkan Pancasila.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 24,
    'Bhinneka Tunggal Ika tertulis pada lambang negara Garuda Pancasila, tepatnya di...',
    '["A. Perisai","B. Cengkeraman","C. Pita yang dicengkeram","D. Bintang","E. Burung Garuda"]'::jsonb,
    'C', 'Semboyan Bhinneka Tunggal Ika tertulis pada pita yang dicengkeram oleh cakar Garuda Pancasila.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 25,
    'Sila kedua Pancasila "Kemanusiaan yang Adil dan Beradab" bermakna...',
    '["A. Menghormati hak asasi manusia","B. Mengutamakan kepentingan pribadi","C. Membedakan derajat manusia","D. Memprioritaskan golongan tertentu","E. Menolak bantuan luar negeri"]'::jsonb,
    'A', 'Sila kedua menjunjung tinggi nilai kemanusiaan, keadilan, dan penghormatan terhadap HAM.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 26,
    'Irian Barat (Papua) resmi menjadi bagian Indonesia pada...',
    '["A. 1945","B. 1949","C. 1950","D. 1963","E. 1976"]'::jsonb,
    'D', 'Irian Barat resmi kembali ke pangkuan Indonesia pada 1963 melalui Perjanjian New York.', 'Sejarah', 'medium'),
  (v_set_id, 'twk', 27,
    'TAP MPR No. XXV/MPRS/1966 mengatur tentang...',
    '["A. Pembubaran PKI","B. Supersemar","C. Pidato presiden","D. Anggaran negara","E. Sidang kabinet"]'::jsonb,
    'A', 'TAP MPR No. XXV/MPRS/1966 tentang Pembubaran PKI dan larangan ajaran komunisme.', 'Sejarah', 'hard'),
  (v_set_id, 'twk', 28,
    'Yang bukan merupakan contoh perilaku penerapan sila keempat Pancasila adalah...',
    '["A. Musyawarah dalam keluarga","B. Mengutamakan keputusan bersama","C. Diskusi terbuka di lingkungan kerja","D. Memutus sendiri tanpa diskusi","E. Rembug desa untuk kepentingan bersama"]'::jsonb,
    'D', 'Sila keempat menekankan musyawarah. Memutus sendiri tanpa diskusi bertentangan dengan sila keempat.', 'Pancasila', 'easy'),
  (v_set_id, 'twk', 29,
    'Pancasila sebagai ideologi terbuka mengandung makna bahwa...',
    '["A. Tidak bisa berubah sama sekali","B. Bersifat kaku dan tertutup","C. Tidak relevan dengan zaman","D. Mampu menyesuaikan diri dengan perkembangan zaman","E. Hanya untuk golongan tertentu"]'::jsonb,
    'D', 'Pancasila sebagai ideologi terbuka bersifat fleksibel dan mampu beradaptasi dengan perkembangan zaman tanpa kehilangan jati diri.', 'Pancasila', 'medium'),
  (v_set_id, 'twk', 30,
    'Yang bukan menjadi bagian dari proklamasi kemerdekaan adalah...',
    '["A. Ir. Soekarno","B. Drs. Moh. Hatta","C. Golongan muda","D. PPKI","E. Tuan RADEN SOEKARNO"]'::jsonb,
    'D', 'PPKI dibentuk setelah proklamasi untuk menyiapkan pemerintahan, bukan penandatangan proklamasi.', 'Sejarah', 'hard');

  -- ═════════════════════════════════════════════════════════════════════════
  -- TIU (Tes Intelegensi Umum) — 35 soal (Verbal, Numerik, Figural, Logis)
  -- ═════════════════════════════════════════════════════════════════════════
  INSERT INTO public.tryout_questions (exam_set_id, subtest, question_number, question_text, options, correct_answer, explanation, category, difficulty) VALUES
  (v_set_id, 'tiu', 31,
    'Jika sebuah persegi panjang memiliki panjang 12 cm dan lebar 8 cm, maka luasnya adalah...',
    '["A. 40 cm2","B. 80 cm2","C. 96 cm2","D. 100 cm2","E. 120 cm2"]'::jsonb,
    'C', 'Luas persegi panjang = panjang x lebar = 12 x 8 = 96 cm².', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 32,
    'Jika 3, 6, 12, 24, ..., maka angka berikutnya adalah...',
    '["A. 30","B. 36","C. 48","D. 60","E. 96"]'::jsonb,
    'C', 'Pola deret: setiap angka dikalikan 2. 3×2=6, 6×2=12, 12×2=24, 24×2=48.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 33,
    'Sinonim dari kata "GIGIH" adalah...',
    '["A. Malas","B. Tekun","C. Lemah","D. Putus asa","E. Acuh"]'::jsonb,
    'B', 'Gigih sinonim dengan tekun, ulet, pantang menyerah.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 34,
    'Antonim dari kata "OPTIMIS" adalah...',
    '["A. Pesimis","B. Realistis","C. Idealistis","D. Materialistis","E. Praktis"]'::jsonb,
    'A', 'Antonim dari optimis adalah pesimis.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 35,
    'Jika sebuah kereta melaju dengan kecepatan 80 km/jam selama 2,5 jam, maka jarak yang ditempuh adalah...',
    '["A. 100 km","B. 150 km","C. 180 km","D. 200 km","E. 220 km"]'::jsonb,
    'D', 'Jarak = kecepatan x waktu = 80 x 2,5 = 200 km.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 36,
    'Semua mamalia memiliki jantung. Paus adalah mamalia. Maka...',
    '["A. Paus tidak memiliki jantung","B. Paus memiliki jantung","C. Paus bukan mamalia","D. Semua mamalia adalah paus","E. Tidak dapat disimpulkan"]'::jsonb,
    'B', 'Karena paus mamalia dan semua mamalia memiliki jantung, maka paus memiliki jantung (silogisme).', 'Logis', 'easy'),
  (v_set_id, 'tiu', 37,
    'Jika harga 5 buku = Rp 75.000, maka harga 1 buku adalah...',
    '["A. Rp 10.000","B. Rp 12.000","C. Rp 15.000","D. Rp 18.000","E. Rp 20.000"]'::jsonb,
    'C', '75.000 / 5 = Rp 15.000 per buku.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 38,
    '12, 14, 16, 20, 22, ... Angka berikutnya adalah...',
    '["A. 24","B. 26","C. 28","D. 30","E. 32"]'::jsonb,
    'B', 'Pola: tambah 2, tambah 2, tambah 4, tambah 2, tambah 2, tambah 4 → 22 + 4 = 26.', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 39,
    'Pohon : Hutan = Pohon : ...',
    '["A. Tanah","B. Akar","C. Daun","D. Kayu","E. Kebun"]'::jsonb,
    'E', 'Pohon tumbuh banyak di hutan. Analogi: pohon tumbuh banyak di kebun.', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 40,
    'Berapakah 25% dari 240?',
    '["A. 50","B. 60","C. 70","D. 80","E. 100"]'::jsonb,
    'B', '25% × 240 = (1/4) × 240 = 60.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 41,
    'Sebuah tabung memiliki jari-jari 7 cm dan tinggi 10 cm. Volume tabung tersebut (π = 22/7) adalah...',
    '["A. 1.400 cm3","B. 1.540 cm3","C. 1.680 cm3","D. 1.720 cm3","E. 2.200 cm3"]'::jsonb,
    'B', 'V = πr²t = (22/7) × 7² × 10 = (22/7) × 49 × 10 = 22 × 70 = 1.540 cm³.', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 42,
    'Kata "KONFLIK" bermakna...',
    '["A. Persahabatan","B. Perselisihan","C. Kerukunan","D. Kesepian","E. Keheningan"]'::jsonb,
    'B', 'Konflik adalah perselisihan atau pertentangan.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 43,
    'Manakah yang bukan bilangan prima?',
    '["A. 2","B. 3","C. 5","D. 7","E. 9"]'::jsonb,
    'E', '9 bukan bilangan prima karena memiliki lebih dari dua faktor (1, 3, 9).', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 44,
    'Dokter : Pasien = Guru : ...',
    '["A. Sekolah","B. Murid","C. Buku","D. Pelajaran","E. Kelas"]'::jsonb,
    'B', 'Dokter melayani pasien; Guru mengajar murid.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 45,
    'Jika 8 + 4 × 3 - 6 ÷ 2 = ...',
    '["A. 17","B. 19","C. 21","D. 23","E. 25"]'::jsonb,
    'A', 'Urutan operasi: 4×3=12, 6÷2=3, maka 8+12-3=17.', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 46,
    'Rata-rata dari 8, 12, 14, 16, 20 adalah...',
    '["A. 12","B. 13","C. 14","D. 15","E. 16"]'::jsonb,
    'C', 'Jumlah = 8+12+14+16+20 = 70. Rata-rata = 70/5 = 14.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 47,
    'Semua guru adalah pendidik. Sebagian pendidik adalah penulis. Maka...',
    '["A. Semua guru adalah penulis","B. Sebagian guru kemungkinan penulis","C. Semua penulis adalah guru","D. Tidak ada guru yang menulis","E. Tidak ada penulis yang pendidik"]'::jsonb,
    'B', 'Sebagian guru mungkin juga penulis, tapi tidak semua (karena hanya sebagian pendidik yang penulis).', 'Logis', 'medium'),
  (v_set_id, 'tiu', 48,
    'Berapakah FPB dari 36 dan 48?',
    '["A. 6","B. 8","C. 12","D. 16","E. 24"]'::jsonb,
    'C', 'FPB 36 dan 48 = 12 (36=2²×3², 48=2⁴×3, irisan = 2²×3=12).', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 49,
    'Antonim dari "PRODUKTIF" adalah...',
    '["A. Aktif","B. Rajin","C. Malas","D. Kreatif","E. Inovatif"]'::jsonb,
    'C', 'Antonim produktif adalah malas.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 50,
    'Jika sebuah mobil menempuh 240 km dengan 20 liter bensin, maka konsumsi BBM per liter adalah...',
    '["A. 8 km/liter","B. 10 km/liter","C. 12 km/liter","D. 14 km/liter","E. 16 km/liter"]'::jsonb,
    'C', 'Konsumsi = 240 km / 20 liter = 12 km/liter.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 51,
    'Pena : Tinta = Lampu : ...',
    '["A. Cahaya","B. Minyak","C. Listrik","D. Api","E. Baterai"]'::jsonb,
    'C', 'Pena butuh tinta untuk menulis; Lampu butuh listrik untuk menyala.', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 52,
    '1, 4, 9, 16, 25, ... Angka berikutnya adalah...',
    '["A. 30","B. 36","C. 40","D. 49","E. 64"]'::jsonb,
    'B', 'Pola bilangan kuadrat: 1², 2², 3², 4², 5², 6²=36.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 53,
    'Sinonim kata "INSOMNIA" adalah...',
    '["A. Tidur","B. Susah tidur","C. Mimpi indah","D. Ngantuk","E. Kelelahan"]'::jsonb,
    'B', 'Insomnia adalah gangguan susah tidur.', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 54,
    'Berapa persen dari 0,25?',
    '["A. 0,25%","B. 2,5%","C. 25%","D. 250%","E. 2.500%"]'::jsonb,
    'C', '0,25 = 25/100 = 25%.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 55,
    'Seekor katak melompat dari titik 0. Lompat pertama ke +5, kedua ke +3, ketiga ke -2, keempat ke -4. Posisi katak sekarang adalah...',
    '["A. -2","B. 0","C. +2","D. +4","E. +6"]'::jsonb,
    'C', '0 + 5 + 3 - 2 - 4 = +2.', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 56,
    'Bentuk sederhana dari 24/36 adalah...',
    '["A. 1/2","B. 2/3","C. 3/4","D. 4/5","E. 5/6"]'::jsonb,
    'B', 'FPB 24 dan 36 = 12, maka 24/12 : 36/12 = 2/3.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 57,
    'Hubungan khusus: MATA : MELIHAT = TELINGA : ...',
    '["A. Mendengar","B. Membau","C. Merasakan","D. Mengecap","E. Berbicara"]'::jsonb,
    'A', 'Mata untuk melihat; Telinga untuk mendengar.', 'Verbal', 'easy'),
  (v_set_id, 'tiu', 58,
    'Jika x + y = 12 dan x - y = 4, maka x = ...',
    '["A. 4","B. 6","C. 8","D. 10","E. 12"]'::jsonb,
    'C', 'Tambah kedua persamaan: 2x = 16, maka x = 8.', 'Numerik', 'medium'),
  (v_set_id, 'tiu', 59,
    'Antonim kata "EGOIS" adalah...',
    '["A. Individualis","B. Altruis","C. Materialis","D. Konsumtif","E. Pragmatis"]'::jsonb,
    'B', 'Antonim egois adalah altruis (mementingkan orang lain).', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 60,
    'Volume kubus dengan panjang sisi 5 cm adalah...',
    '["A. 25 cm3","B. 75 cm3","C. 100 cm3","D. 125 cm3","E. 150 cm3"]'::jsonb,
    'D', 'V kubus = s³ = 5³ = 125 cm³.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 61,
    'Hewan : Veterinarian = Tanaman : ...',
    '["A. Petani","B. Agronom","C. Insinyur","D. Arsitek","E. Dokter"]'::jsonb,
    'B', 'Hewan ditangani dokter hewan (veterinarian); Tanaman ditangani ahli pertanian/agronom.', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 62,
    '4, 9, 16, 25, ... Angka berikutnya adalah...',
    '["A. 30","B. 36","C. 40","D. 49","E. 64"]'::jsonb,
    'B', 'Pola kuadrat: 2², 3², 4², 5², 6²=36.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 63,
    'Hasil dari 0,75 × 0,2 adalah...',
    '["A. 0,015","B. 0,15","C. 1,5","D. 15","E. 150"]'::jsonb,
    'B', '0,75 × 0,2 = 0,15.', 'Numerik', 'easy'),
  (v_set_id, 'tiu', 64,
    'Kalimat "Saya memasak nasi goreng" yang setara dengan kalimat pasif adalah...',
    '["A. Nasi goreng dimasak oleh saya","B. Saya dimasak nasi goreng","C. Nasi goreng memasak saya","D. Saya memasak nasi goreng (sama)","E. Nasi goreng saya masak"]'::jsonb,
    'A', 'Bentuk pasif: "Nasi goreng dimasak oleh saya".', 'Verbal', 'medium'),
  (v_set_id, 'tiu', 65,
    'Jika 3 orang dapat menyelesaikan pekerjaan dalam 12 hari, maka 6 orang dapat menyelesaikan dalam...',
    '["A. 4 hari","B. 6 hari","C. 8 hari","D. 10 hari","E. 24 hari"]'::jsonb,
    'B', 'Berbanding terbalik: 3 × 12 = 6 × x, maka x = 6 hari.', 'Numerik', 'medium');

  -- ═════════════════════════════════════════════════════════════════════════
  -- TKP (Tes Karakteristik Pribadi) — 45 soal
  -- ═════════════════════════════════════════════════════════════════════════
  INSERT INTO public.tryout_questions (exam_set_id, subtest, question_number, question_text, options, scores, explanation, category, difficulty) VALUES
  (v_set_id, 'tkp', 66,
    'Anda diminta menyelesaikan tugas mendadak yang mendesak. Apa yang Anda lakukan?',
    '["A. Langsung mengerjakan dengan prioritas utama","B. Berdiskusi dulu dengan rekan","C. Menunggu instruksi atasan lebih lanjut","D. Mendelegasikan ke rekan kerja","E. Meminta penundaan karena tidak sempat"]'::jsonb,
    '{"A":5,"B":4,"C":2,"D":3,"E":1}'::jsonb,
    'Tugas mendesak menunjukkan prioritas; mengerjakannya langsung menunjukkan inisiatif dan tanggung jawab.',
    'Pelayanan Publik', 'medium'),
  (v_set_id, 'tkp', 67,
    'Rekan kerja Anda melakukan kesalahan yang merugikan tim. Apa sikap Anda?',
    '["A. Melaporkan langsung ke atasan","B. Menyampaikan secara pribadi untuk perbaikan","C. Membiarkan saja karena bukan urusan","D. Menyebarkan agar semua tahu","E. Menyalahkan rekan di depan umum"]'::jsonb,
    '{"A":3,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Pendekatan paling bijak: sampaikan secara pribadi untuk perbaikan tanpa mempermalukan di depan umum.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 68,
    'Anda mendapatkan tugas baru yang belum pernah Anda kuasai. Sikap Anda...',
    '["A. Menolak karena tidak mampu","B. Menerima dengan senang hati dan belajar","C. Menerima tapi setengah hati","D. Menyerahkan ke orang lain","E. Menunggu arahan detail dari atasan"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":2}'::jsonb,
    'Inisiatif belajar dan berkembang adalah ciri profesional yang adaptif.',
    'Profesionalisme', 'easy'),
  (v_set_id, 'tkp', 69,
    'Warga datang dengan keluhan yang sangat emosional. Apa yang Anda lakukan?',
    '["A. Memotong pembicaraan untuk efisiensi","B. Mendengarkan dengan empati dan mencari solusi","C. Meminta warga lain yang lebih sabar","D. Mengarahkan ke bagian lain tanpa solusi","E. Meninggalkan ruangan karena tidak nyaman"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Pelayanan publik yang baik membutuhkan empati, mendengar, lalu bertindak untuk solusi.',
    'Pelayanan Publik', 'easy'),
  (v_set_id, 'tkp', 70,
    'Tim Anda gagal mencapai target. Sikap Anda sebagai anggota tim...',
    '["A. Menyalahkan anggota tertentu","B. Menganalisa penyebab dan belajar bersama","C. Diam saja dan menunggu","D. Mengundurkan diri dari tim","E. Menyalahkan atasan"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Budaya belajar dari kegagalan dan kolaborasi untuk perbaikan mencerminkan profesionalisme.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 71,
    'Atasan memberikan instruksi yang menurut Anda kurang tepat. Anda akan...',
    '["A. Langsung menolak","B. Mengerjakan sambil memberi masukan sopan","C. Menggerutu tapi tetap mengerjakan","D. Tidak mengerjakan","E. Melapor ke atasan yang lebih tinggi"]'::jsonb,
    '{"A":2,"B":5,"C":2,"D":1,"E":2}'::jsonb,
    'Disiplin pada instruksi atasan sambil tetap memberi masukan yang konstruktif adalah sikap dewasa.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 72,
    'Anda memiliki kesempatan untuk promosi jabatan. Rekan kerja Anda juga menginginkan posisi yang sama. Sikap Anda...',
    '["A. Bersaing secara sehat dan sportif","B. Menjatuhkan rekan kerja","C. Mundur untuk menghindari konflik","D. Melobi atasan agar dipilih","E. Menyebarkan berita negatif tentang rekan"]'::jsonb,
    '{"A":5,"B":1,"C":2,"D":1,"E":1}'::jsonb,
    'Kompetisi sehat dan sportif mencerminkan profesionalisme. Menjatuhkan rekan bertentangan dengan etika.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 73,
    'Anda bekerja dalam tim multibudaya. Cara terbaik berkomunikasi adalah...',
    '["A. Memaksakan budaya mayoritas","B. Menghormati perbedaan dan mencari kesamaan","C. Menghindari topik sensitif","D. Memisahkan kelompok","E. Meniru cara berkomunikasi satu budaya"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":2}'::jsonb,
    'Menghormati keberagaman budaya dan mencari kesamaan adalah sikap inklusif yang ideal.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 74,
    'Anda melihat atasan Anda bersikap tidak adil kepada bawahan. Sikap Anda...',
    '["A. Diam saja karena takut","B. Menyampaikan kepedulian dengan cara yang tepat","C. Mengeluh ke sesama bawahan","D. Melapor ke inspektorat","E. Memancing konflik di kantor"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":3,"E":1}'::jsonb,
    'Menyampaikan kepedulian secara privat dan konstruktif adalah integritas moral yang penting.',
    'Profesionalisme', 'hard'),
  (v_set_id, 'tkp', 75,
    'Anda memiliki ide brilian untuk meningkatkan layanan. Tindakan Anda...',
    '["A. Menyimpan ide untuk diri sendiri","B. Menyampaikan ke atasan dengan data pendukung","C. Menunggu sampai ada perintah","D. Menerapkan sendiri tanpa izin","E. Menjual ide ke pihak luar"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Menyampaikan ide melalui jalur resmi dengan data adalah cara profesional menyumbang inovasi.',
    'Pelayanan Publik', 'medium'),
  (v_set_id, 'tkp', 76,
    'Bawahan Anda melakukan kesalahan berulang meski sudah ditegur. Sikap Anda...',
    '["A. Memecat langsung","B. Membimbing dengan sabar dan coaching","C. Mengeluh ke atasan","D. Membiarkan saja","E. Membentak di depan umum"]'::jsonb,
    '{"A":2,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Fungsi manager adalah mengembangkan bawahan; coaching adalah pendekatan kepemimpinan modern.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 77,
    'Warga mengeluh tentang layanan yang lambat. Sebagai petugas, Anda akan...',
    '["A. Berdalih bahwa semua juga lambat","B. Meminta maaf dan berusaha mempercepat","C. Menyalahkan sistem","D. Meminta warga menunggu lebih lama","E. Meninggalkan loket"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Pelayanan publik yang prima dimulai dari sikap peduli, minta maaf, dan bertindak cepat.',
    'Pelayanan Publik', 'easy'),
  (v_set_id, 'tkp', 78,
    'Anda diminta memimpin rapat. Gaya kepemimpinan Anda...',
    '["A. Mengarahkan tanpa mendengar","B. Memfasilitasi diskusi terbuka","C. Mendominasi pembicaraan","D. Mendelegasikan ke orang lain","E. Memutus tanpa pertimbangan"]'::jsonb,
    '{"A":2,"B":5,"C":2,"D":3,"E":1}'::jsonb,
    'Kepemimpinan kolaboratif yang memfasilitasi diskusi menghasilkan keputusan lebih baik.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 79,
    'Anda menerima tugas yang tidak sesuai job description. Sikap Anda...',
    '["A. Menolak mentah-mentah","B. Menerima dengan bijaksana jika mampu","C. Menolak dengan alasan sibuk","D. Mengerjakan sambil menggerutu","E. Melapor ke serikat pekerja"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":2}'::jsonb,
    'Profesional yang adaptif menerima tantangan baru selama masih dalam kapasitas yang wajar.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 80,
    'Anda ditunjuk mewakili kantor dalam sebuah forum penting. Persiapan Anda...',
    '["A. Datang tanpa persiapan","B. Mempersiapkan materi dengan matang","C. Menyalin materi rekan","D. Meminta bahan dari atasan","E. Meminta digantikan orang lain"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":2,"E":1}'::jsonb,
    'Tanggung jawab delegasi menuntut persiapan matang demi citra institusi.',
    'Profesionalisme', 'easy'),
  (v_set_id, 'tkp', 81,
    'Rekan kerja Anda membutuhkan bantuan saat Anda juga sibuk. Anda akan...',
    '["A. Menolak dengan alasan sibuk","B. Membantu sebisa mungkin sambil menghargai prioritas","C. Meminta bantuan balik","D. Mengabaikan","E. Menyuruh orang lain"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Solidaritas profesional dengan mengelola prioritas adalah ciri kolaborasi sehat.',
    'Jejaring Kerja', 'easy'),
  (v_set_id, 'tkp', 82,
    'Ada perubahan regulasi yang memengaruhi pekerjaan Anda. Sikap Anda...',
    '["A. Bersikukuh dengan cara lama","B. Mempelajari dan menyesuaikan diri","C. Mengeluh ke rekan","D. Menolak perubahan","E. Melanggar regulasi"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Adaptasi terhadap perubahan regulasi adalah bagian dari profesionalisme dan akuntabilitas.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 83,
    'Anda melihat同事 (rekan) menerima suap. Anda akan...',
    '["A. Ikut menerima","B. Melaporkan ke atasan atau pihak berwenang","C. Diam karena bukan urusan","D. Ikut menikmati","E. Memeras rekan"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Integritas adalah menolak dan melaporkan pelanggaran meskipun sulit.',
    'Integritas', 'medium'),
  (v_set_id, 'tkp', 84,
    'Warga meminta informasi yang menjadi rahasia negara. Anda akan...',
    '["A. Memberikan sebagian informasi","B. Menolak dengan penjelasan yang sopan","C. Memberikan seluruh informasi","D. Meminta imbalan","E. Mengarahkan ke sumber lain secara sembarangan"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Penjaga kerahasiaan informasi negara adalah bagian dari tugas aparatur negara.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 85,
    'Anda bekerja di bawah tekanan tinggi dan mendekati deadline. Anda akan...',
    '["A. Panik dan tidak fokus","B. Membuat prioritas dan bekerja terstruktur","C. Menyerah dan menunda","D. Menyalahkan rekan","E. Meninggalkan pekerjaan"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Manajemen stres dan kemampuan memprioritaskan adalah kompetensi penting.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 86,
    'Ada konflik internal yang berpotensi memecah tim. Anda akan...',
    '["A. Memperkeruh situasi","B. Menjadi mediator netral","C. Memilih salah satu pihak","D. Menghindar","E. Menyebarkan gosip"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Mediasi yang netral menjaga keharmonisan tim dan menunjukkan kedewasaan.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 87,
    'Anda diberikan wewenang lebih dari biasanya. Sikap Anda...',
    '["A. Menyalahgunakan wewenang","B. Menggunakan dengan bertanggung jawab","C. Menolak karena tanggung jawab besar","D. Mendelegasikan semua","E. Memamerkan wewenang"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":2,"E":1}'::jsonb,
    'Wewenang harus dijalankan dengan akuntabilitas dan integritas.',
    'Integritas', 'medium'),
  (v_set_id, 'tkp', 88,
    'Anda diminta bekerja lembur yang tidak dibayar. Sikap Anda...',
    '["A. Langsung menolak","B. Mendiskusikan kompensasi dengan baik-baik","C. Diam dan mengerjakan dengan menggerutu","D. Mengajak rekan untuk mogok","E. Meninggalkan pekerjaan tepat waktu"]'::jsonb,
    '{"A":2,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Komunikasi asertif untuk kompensasi yang adil adalah pendekatan dewasa.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 89,
    'Anda memiliki kesempatan untuk mengikuti pelatihan. Sikap Anda...',
    '["A. Mengirim orang lain saja","B. Mengikuti dengan antusias","C. Mengikuti jika diperintah","D. Menolak karena repot","E. Mengikuti tetapi tidak fokus"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Pengembangan kompetensi melalui pelatihan adalah investasi karier.',
    'Profesionalisme', 'easy'),
  (v_set_id, 'tkp', 90,
    'Anda melihat pemborosan anggaran di unit kerja. Tindakan Anda...',
    '["A. Ikut-ikutan","B. Menyampaikan untuk efisiensi","C. Diam saja","D. Mengambil bagian","E. Mengeluh tanpa bertindak"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Integritas mencakup keberanian menyampaikan untuk kebaikan organisasi.',
    'Integritas', 'medium'),
  (v_set_id, 'tkp', 91,
    'Warga meminta formulir yang tidak sesuai prosedur. Anda akan...',
    '["A. Memberikan formulir","B. Menjelaskan prosedur yang benar dengan ramah","C. Memarahi warga","D. Mengabaikan","E. Meminta warga mengurus sendiri"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Mendidik warga tentang prosedur dengan ramah adalah bagian dari pelayanan informatif.',
    'Pelayanan Publik', 'easy'),
  (v_set_id, 'tkp', 92,
    'Anda memiliki pendapat berbeda dengan mayoritas tim. Anda akan...',
    '["A. Diam karena takut berbeda","B. Menyampaikan dengan argumentasi yang baik","C. Memaksakan pendapat","D. Menyabotase keputusan tim","E. Mundur dari tim"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Asertivitas dalam menyampaikan pendapat dengan data adalah ciri kepemimpinan.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 93,
    'Anda lelah fisik dan mental setelah bekerja keras. Anda akan...',
    '["A. Memaksakan diri bekerja terus","B. Mengambil cuti untuk pemulihan","C. Mengeluh tanpa bertindak","D. Mengurangi kualitas kerja","E. Meninggalkan tugas"]'::jsonb,
    '{"A":2,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Self-care dan work-life balance penting untuk menjaga kualitas kerja jangka panjang.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 94,
    'Anda diminta memberikan testimoni positif tentang layanan yang sebenarnya bermasalah. Anda akan...',
    '["A. Memberikan testimoni palsu","B. Menyampaikan kebenaran secara berimbang","C. Menolak dengan kasar","D. Menghindari pertanyaan","E. Menyesatkan publik"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Kejujuran dan integritas lebih penting daripada tekanan untuk menyenangkan pihak lain.',
    'Integritas', 'medium'),
  (v_set_id, 'tkp', 95,
    'Tim Anda terdiri dari berbagai latar belakang. Anda akan...',
    '["A. Memilih anggota yang sependapat","B. Menghargai keragaman dan membangun sinergi","C. Membentuk sub-kelompok","D. Memaksakan keseragaman","E. Memisahkan diri"]'::jsonb,
    '{"A":2,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Inklusivitas dan sinergi dari keberagaman menghasilkan tim yang lebih kuat.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 96,
    'Anda menerima keluhan berulang dari warga tentang hal yang sama. Sikap Anda...',
    '["A. Mengabaikan","B. Menganalisa akar masalah dan mencarikan solusi","C. Menyalahkan warga","D. Memindahkan tanggung jawab","E. Mengeluh ke rekan"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Pendekatan berbasis masalah (problem solving) adalah inti perbaikan layanan publik.',
    'Pelayanan Publik', 'medium'),
  (v_set_id, 'tkp', 97,
    'Anda ditawari proyek sampingan dari rekan yang berbenturan dengan pekerjaan utama. Anda akan...',
    '["A. Menerima langsung","B. Menolak karena khawatir benturan kepentingan","C. Menerima jika tertutup","D. Minta persentase besar","E. Mengelak tanpa alasan"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Menghindari benturan kepentingan (conflict of interest) adalah etika profesional.',
    'Integritas', 'hard'),
  (v_set_id, 'tkp', 98,
    'Anda baru pertama kali ditempatkan di unit baru. Tindakan Anda...',
    '["A. Langsung menilai unit lama","B. Belajar dan beradaptasi dengan budaya baru","C. Mengeluh ke senior","D. Menunggu instruksi detail","E. Menghindar dari interaksi"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":2,"E":1}'::jsonb,
    'Adaptabilitas dan keterbukaan belajar adalah sikap profesional saat rotasi.',
    'Profesionalisme', 'easy'),
  (v_set_id, 'tkp', 99,
    'Anda menjadi panitia kegiatan besar. Pendekatan Anda...',
    '["A. Memimpin dengan mengabaikan masukan","B. Berkoaborasi dengan panitia dan menerima masukan","C. Mendelegasikan semua","D. Memaksakan keinginan sendiri","E. Menghindari keputusan sulit"]'::jsonb,
    '{"A":2,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Kepemimpinan kolaboratif menghasilkan kegiatan yang lebih berkualitas dan tim yang solid.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 100,
    'Warga sulit memahami informasi yang kompleks. Anda akan...',
    '["A. Memaksa warga untuk paham sendiri","B. Menggunakan bahasa sederhana dan peragaan","C. Meninggalkan warga","D. Mengirimkan dokumen saja","E. Meminta warga bertanya ke orang lain"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":2,"E":1}'::jsonb,
    'Komunikasi yang efektif menyesuaikan gaya bahasa dengan kemampuan audiens.',
    'Pelayanan Publik', 'easy'),
  (v_set_id, 'tkp', 101,
    'Anda diminta mewakili tim dalam presentasi, padahal rekan lain lebih kompeten. Anda akan...',
    '["A. Menolak tanpa alasan","B. Menerima dan belajar cepat","C. Meminta digantikan","D. Memaksakan presentasi seadanya","E. Meminta ganti rugi"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Tanggung jawab yang diberikan adalah kesempatan untuk berkembang; inisiatif dan adaptasi kunci.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 102,
    'Anda mendapat informasi sensitif tentang rekan kerja. Anda akan...',
    '["A. Menyebarkan untuk alasan apa pun","B. Menjaga kerahasiaan dan tidak menyalahgunakan","C. Menggunakan sebagai alat tawar","D. Mengunggah ke media sosial","E. Menyimpan sambil menunggu momen"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Kerahasiaan informasi dan tidak menyalahgunakannya adalah etika dasar.',
    'Integritas', 'medium'),
  (v_set_id, 'tkp', 103,
    'Anda ditugaskan ke daerah terpencil. Sikap Anda...',
    '["A. Menolak keras","B. Menerima dengan komitmen untuk mengabdi","C. Meminta jaminan khusus","D. Mengeluh kepada keluarga","E. Meminta pindah sebelum ditempatkan"]'::jsonb,
    '{"A":1,"B":5,"C":2,"D":1,"E":1}'::jsonb,
    'Semangat pengabdian dan willingness to serve adalah nilai luhur ASN.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 104,
    'Anda ragu dengan keputusan yang diambil atasan. Anda akan...',
    '["A. Mengikuti tanpa bertanya","B. Meminta penjelasan lebih lanjut dengan sopan","C. Mengeluh ke rekan","D. Menolak mentah","E. Memanipulasi situasi"]'::jsonb,
    '{"A":2,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Komunikasi dua arah yang sopan untuk klarifikasi mencerminkan profesionalisme.',
    'Profesionalisme', 'easy'),
  (v_set_id, 'tkp', 105,
    'Warga mengeluh tentang kebijakan baru yang kurang populer. Anda akan...',
    '["A. Ikut menyalahkan kebijakan","B. Menjelaskan tujuan dan manfaat kebijakan dengan sabar","C. Memilih menghindari topik","D. Meminta warga mengadu sendiri","E. Mengeluh ke rekan tentang kebijakan"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Sikap proaktif menjelaskan kebijakan menunjukkan peran edukatif aparatur negara.',
    'Pelayanan Publik', 'medium'),
  (v_set_id, 'tkp', 106,
    'Anda dimintai tolong rekan untuk menyelesaikan tugasnya. Anda akan...',
    '["A. Menolak langsung","B. Membantu jika masih dalam kapasitas","C. Meminta imbalan","D. Membantu tapi mengabaikan tugas sendiri","E. Menyebarkan ke banyak orang"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":1}'::jsonb,
    'Solidaritas profesional dengan tetap memprioritaskan tugas utama.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 107,
    'Anda ditawari promosi dengan syarat melangkahi senior. Anda akan...',
    '["A. Menerima untuk карьер","B. Menerima jika itu sah","C. Menolak karena pertimbangan etika tim","D. Melapor ke atasan lain","E. Meminta bonus khusus"]'::jsonb,
    '{"A":2,"B":3,"C":5,"D":2,"E":1}'::jsonb,
    'Pertimbangan etika dan dampak terhadap keharmonisan tim penting dalam promosi.',
    'Integritas', 'hard'),
  (v_set_id, 'tkp', 108,
    'Anda memiliki tugas rutin yang membosankan. Anda akan...',
    '["A. Meninggalkan begitu saja","B. Mencari cara untuk meningkatkan efisiensi","C. Mengeluh setiap hari","D. Meminta tugas baru","E. Menurunkan kualitas"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":2,"E":1}'::jsonb,
    'Inovasi pada tugas rutin menunjukkan ownership dan profesionalisme.',
    'Profesionalisme', 'medium'),
  (v_set_id, 'tkp', 109,
    'Anda menjadi target bully rekan kerja. Anda akan...',
    '["A. Balas membully","B. Melaporkan ke atasan atau HR untuk perlindungan","C. Diam dan menyimpan dendam","D. Menghindari pekerjaan","E. Menyebarkan identitas pelaku"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Mencari perlindungan melalui jalur resmi adalah sikap dewasa dan sehat.',
    'Jejaring Kerja', 'medium'),
  (v_set_id, 'tkp', 110,
    'Anda melihat potensi fraud di unit kerja. Anda akan...',
    '["A. Ikut terlibat","B. Melaporkan melalui whistle blower system","C. Diam untuk menjaga hubungan","D. Ikut menikmati hasilnya","E. Menyimpan untuk laporan nanti"]'::jsonb,
    '{"A":1,"B":5,"C":1,"D":1,"E":2}'::jsonb,
    'Integritas berani menolak fraud melalui whistle blower system yang disediakan.',
    'Integritas', 'hard');
END $$;